### PR TITLE
Digi WiFi status and more debug

### PR DESCRIPTION
**Pull request by neilh10**
This is something I've found useful.  Its offered for develop. I've tested it in my private branch, and it compiles on a derivative of EnviroDIY/ModularSensors:develop menu_a_la_carte.ino - however that has exceeded the 1300488 bytes of flash, and its a lot of work to go back and rework the test build env.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
I don't have any more success in getting a signal strength or a NIST response whether I ensure I have an IP address or not.

**Comment by neilh10** [comment]
The only other thing I do differently than what I submitted - i know you had some other insights - but I do this

gsmModem.sendAT(GF("SO"),100);

SO command
0x100 | For cyclic sleep .. **Currentimplementation does not support this bit being turned off**
-- | --

Unfortunately I'm not going ot have any time to merge the new release to my fork till at least Thursday and possibly next week.

**Comment by SRGDamia1** [comment]
I think I have everything working for the WiFi again.  There were two problems - the switch from NIST to Google for linking to check connection didn't work because Google wasn't replying and the hard-coded NIST IP was for a NIST server that went down.

I don't want to wait for the internet connection/IP registration during modem set-up.  I'd rather save that for the next request for signal strength or use of the modem.

**Comment by neilh10** [comment]
Great to hear its working.  I think its fantastic all the coverage you are doing, though it would be nice to have  some release notes about what actually gets checked. I guess not everything can be so a little hint as to the focus would be valuable.

**Pull request closed without merging**
