### PR TITLE
Implemented real calculated variables

### LINKED ISSUE #127: Create generic calculated variables
That is calculated variables where the value depends on more than one sensor's variable result, or on one variable result and any other not-permanently-fixed value.

See discussion in 5e2c6f05c6d145c199ec5cb13f6d61090da3d7d4 and #125.

I think this can be done, but it will have to be done carefully so as not to have timing errors in arrays.  Perhaps a new Boolean flag could be added to the variable base object alerting the array to skip this variable until the end.

Note that there is already support for sensors that have calculated results based only on other values obtained in one reading from that sensor.  ie, the VWC from the 5TM is a result calculated by this library, but that result is nearly always a desired return from the sensor and the inputs for that calculation come entirely from one reading on the 5TM.  It would be easy to add a variety of other calculations, like altitude from any pressure sensor, but I don't think that particular calculation is nearly universally desired enough to both making it standard in this library.

### PR DESCRIPTION
**Pull request by SRGDamia1**
Wahoo!  Closes #127 

@aufdenkampe and @fisherba please test out the baro_rho_correction example now.  You no longer have to do any messing with the text strings and can use the basic "log()" function.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
The headers for the calculated variables will be in their proper place with all of the others, and the calculated results will even appear in testing mode.

**Comment by aufdenkampe** [comment]
@SRGDamia1, this is awesome. Thank you for taking the initiative to do this. I think it will significantly simplify some near-future work and open up many doors for new features. Thank you.

I'll try to test soon.
cc: @bschulz1701 & @awickert

**Comment by fisherba** [comment]
Awesome! I will have a station with me this week and will take some time to test it. Maybe you can take a peek at the TP Downhole sensor if we are able to stop by. It's pretty cool.

**Comment by SRGDamia1** [comment]
TP Downhole sensor?

**Comment by fisherba** [comment]
Temperature and Pressure sensor... for wells. (They had fun with the name.) It's the Northern Widget enclosure of the MS5803-2BA (@bschulz1701 and @awickert did a clever job of making it compact and bulletproof).

**Comment by fisherba** [comment]
P.S. It's a crazy economical way to get millimeter precision. I'm not going to publish their price!

**Comment by SRGDamia1** [comment]
I just added a bunch of restructuring to this.  **THIS DESTROYS BACKWARDS COMPATIBILITY!!**  I've updated the examples, please update your code.

**Comment by fisherba** [comment]
So far I can't get the sketch to proceed at all. It stalls out as below. Since it's not even proceeding to measurements, I don't know what debugging would be useful to you. 

```
Now running baro_rho_correction.ino on Logger XXXXX
Logger timezone is UTC-5
RTC timezone is UTC
```

**Comment by SRGDamia1** [comment]
I'm sorry. I'll try to check it out once my kids are healthy again. (Hopefully tomorrow.)

**Comment by SRGDamia1** [comment]
The sketch seems to be working fine for me.  Are you sure you have everything up-to-date?  You need to be at a84934eebc1fadef8b372dc0251cb3b127c8f71a for the library and the example sketch.  I made changes that broke backwards compatibility, so anything you have based on an example from earlier than that will fail.

**Comment by fisherba** [comment]
I am finally able to test this and deployed a stations using the new calculated variables sketch yesterday. It worked for me (using EnviroDIY_ModularSensors@>=0.11.6) with one interesting caveat. I need to have the I2C pin on the Mayfly always on (as 3v3, not "3v3 switched") when MS5803 sensors are connected for the sketch to proceed past: 
```
Initializing logger NAME to record at 15 minute intervals ...    ... Success!
```
If just the BME280 is attached to I2C, the sketch proceeds just fine. Maybe the sketch is trying to talk to the I2C devices before their power is switch on? 

At any rate, if I2C power is set to always on, then the calculated variables sketch works. ....And that glitch isn't exactly related to this pull request, but I figured I would tell you my observations....

**Comment by aufdenkampe** [comment]
I just did some testing, and this ModularSensors *calcVar* branch as of June 4, 2018 fixes the weird issues that we've been noticing with Maxbotix sonar, as described in https://www.envirodiy.org/topic/minor-glitch-reading-maxbotix-mb7389-with-mayfly/#post-12346

This may confirm that the Sonar issue described in #128 was also fixed.

**Pull request merged**
