### PR TITLE
Radically simplified modems in sketches by making a modem parent class

### PR DESCRIPTION
**Pull request by SRGDamia1**
Now each modem is implemented as it's own instance of the modem class so all you need to do is create the modem object.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, is this ready for testing? I might try it tonight, as I have a few things to program in the next few days.

**Comment by SRGDamia1** [comment]
Where are you using issues tracing the code?

**Comment by aufdenkampe** [comment]
@SRGDamia1, is this branch ready for testing?

**Comment by fisherba** [comment]
I'm about to upload some tests...

**Comment by fisherba** [comment]
I am using logging to MMW and have the following result:

```
Now running logging_to MMW.ino on Logger XXXXX

Using ModularSensors Library version 0.22.0
Logger timezone is set to UTC -5
RTC timezone is set to UTC
A modem has been tied to this logger!
Push button on pin 21 at any time to enter sensor testing mode.
Current RTC time is: 2019-05-23T17:04:50-05:00
Logger setup finished!
Attempting to synchronize RTC with NIST
Bad timestamp, not setting clock.

Setting up sensors...
Data will be saved as XXXXX_2019-05-23.csv
Putting processor to sleep
```
Which looks like a bad response, but my Hologram account is indicating activity. Yet in all of my sensor tests I'm getting:
```
SIMCom SIM800 at Pin19 reports RSSI is -9999 decibelMiliWatt
SIMCom SIM800 at Pin19 reports signalPercent is -9999 percent
```


I also tried uBeeTest.ino, but realized that wasn't a recent addition to the library. I'm not clear on what it's trying to test other than pin connections. It wasn't causing a data usage response on Hologram.

Seems like not a full success. Any debugging you'd like to see @SRGDamia1 

P.S. I'm excited about this modem simplification. Thank you!

**Comment by fisherba** [comment]
Also...
I get a 504 response when logging. I'm going to make some real UUIDs while I wait for your thoughts so it can be a full test.

**Comment by SRGDamia1** [comment]
@fisherba - yes ubee test was just a pin test 

Can you turn on more debugging? - both standard and deep in gprsbee

**Comment by SRGDamia1** [comment]
And verify which version of TinyGSM you're using - at least 0.7.5 - something else I did seems to have caused problems for the SIM800:  https://github.com/vshymanskyy/TinyGSM/issues/286#issuecomment-495369716

Anything with 2G is kind-of a pain for me at this point.  I'll try to test soon.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for that update. We're still using a lot of the GPRSBee 2G radios. Are you aware if there is a differences between GPRSBee rev6b vs. rev7b? 

@gcutrell seems to have some code that works on rev6b but not rev7b (but it was based on ModularSensors v0.21.2).

**Comment by SRGDamia1** [comment]
I have no idea if there's a difference.  I don't know if @s-hicks2 has any of the rev7's; I don't.

**Comment by SRGDamia1** [comment]
What do you think of the changed modem constructors?  Is it the sort-of simplification you were hoping for?

**Comment by fisherba** [comment]
name=TinyGSM
version=0.7.5


added to libdeps (Sarah knows I need this but in case anyone else is playing along at home):
    https://github.com/vshymanskyy/StreamDebugger.git 



[modem_log_baf_20190523.txt](https://github.com/EnviroDIY/ModularSensors/files/3214462/modem_log_baf_20190523.txt)

**Comment by fisherba** [comment]
The modem constructor totally works for me.

So... I hit comment too soon on the text log for the debugging, but you should know that Hologram is still indicating data use during RTC sync and during logging.

**Comment by fisherba** [comment]
And it was logging even though we were getting 504 response?!
http://data.envirodiy.org/sites/fisherba_desk/

**Comment by fisherba** [comment]
The same behavior (504, -9999's, and logging to the data portal) was replicated by @gcutrell.

**Comment by fisherba** [comment]
I tested this morning on bf667dc33ef7e48a38fd55a9adc9579331c344c4 (most recent commit) and the response code is 201, the modem is drawing data according to Holorgram, the data is logging at EnviroDIY, but the RSSI and Signal Percent still read at -9999 in both testing and logging mode.

**Comment by SRGDamia1** [comment]
Hm.  It was working for me on Friday night with all the modems I could get my hands on (GPRSBee4 and 6, UBee 201, XBee 3G, LTE-M and wifi in Transparent, and XBee 3G and LTE-M in bypass).  I was having trouble with the ESP8266, but I think that's related to my attempt to update it's firmware not the code.

Can you give a more detailed log?

**Comment by fisherba** [comment]
Is the GPRSBee Rev 7 potentially different enough? I only see an option for version 6 in menu a la carte. 

Turning on debugging, etc now.

**Comment by SRGDamia1** [comment]
I know nothing about Rev7 - I *assume* it's the same as the R6, but I haven't seen a schema or any other documentation on it.

**Comment by aufdenkampe** [comment]
Using the GPRSBee Rev 6b and a separate/freshly independent set of code, I just got the same result as @fisherba (i.e. radio connects but `RSSI` & `signalPercent` both give -9999).

Library version:
```.ini
; Using ModularSensors *modems* branch (v0.22.1) as of 2019-05-28: head, 62 commits ahead of master (v0.21.4)
    https://github.com/EnviroDIY/ModularSensors.git#abf34e6233da858c33db147eeb96825df5a3570a
```

Code sketch is at https://github.com/LimnoTech/EnviroDIY_deployments/tree/master/deploy-VLAWMO/VLAWMO-2

My output also gives some odd numbers. See my output below (note my UUIDs are bad, but Hologram shows that the radio was connecting):
```
Now running VLAWMO-2.ino on Logger VLAWMO-2

Using ModularSensors Library version 0.22.1
Logger timezone is set to UTC -6
RTC timezone is set to UTC
A modem has been tied to this logger!
Push button on pin 21 at any time to enter sensor testing mode.
Current RTC time is: 2019-05-29T04:40:42-06:00
Logger setup finished!
Attempting to synchronize RTC with NIST
Clock already within 5 seconds of time.
Setting up sensors...
Data will be saved as VLAWMO-2_2019-05-29.csv
Putting processor to sleep

------------------------------------------
824957485513
824957485613824957485713824957485713
824957485713824957494813824957494813
824957494813824957494813824957494813
824957494813

 \/---- Line Saved to SD Card ----\/
2019-05-29 04:42:00,1909,3090,4.836,22.50,-9999,-9999



Sending data to data.envirodiy.org
-- Response Code --
403
------------------------------------------

------------------------------------------
Entering sensor testing mode
------------------------------------------
824957485713824957494813824957494813824957494913824957494913
824957495013824957494813824957485713
824957485513824957485413824957484813
82495552491382495450571382
824954505713
Current logger time is 2019-05-29T04:42:50-06:00
-----------------------
MaxBotixMaxSonar at sonarStream_trigger-1 reports distance is 1795 millimeter
gageHeight is calculated to be 3204 millimeter
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.791 volt
MaximDS3231 at I2C_0x68 reports temperatureDatalogger is 22.50 degreeCelsius
SIMCOM SIM800H at Pin19 reports RSSI is -9999 decibelMiliWatt
SIMCOM SIM800H at Pin19 reports signalPercent is -9999 percent
-----------------------
------------------------------------------
824954505713824954505713824954514813824954514813824954514813824954514813824954514813824954514813824954514813824954505713824954
824956525713

824956534813
824956535013
824956535113
Current logger time is 2019-05-29T04:42:56-06:00
-----------------------
MaxBotixMaxSonar at sonarStream_trigger-1 reports distance is 1830 millimeter
gageHeight is calculated to be 3169 millimeter
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.791 volt
MaximDS3231 at I2C_0x68 reports temperatureDatalogger is 22.50 degreeCelsius
SIMCOM SIM800H at Pin19 reports RSSI is -9999 decibelMiliWatt
SIMCOM SIM800H at Pin19 reports signalPercent is -9999 percent
-----------------------
```

**Comment by SRGDamia1** [comment]
Your sketch works fine for me on the GPRSBeeR6.  There must be something different about the R7.

It took me a bit to puzzle out all the odd numbers. I didn't get them until I actually hooked up the sonar.   But they are just because I forgot to change one of the debugging statements in the MaxBotix cpp when I changed the way you turn on the debugging with flags.  Those numbers are just the ascii number of the continuous stream from the sonar (824956534813=R1850\r).  I've fixed that so you should only see that if you actually intentionally turn on the Maxbotix debugging.  But that doesn't have anything to do with the modem issue.

Are you sure you have TinyGSM 0.7.9?  Turn on all the modem debugging, LoggerModem, GPRSBee, and GPRSBee deep.  You can either open the library files and un-comment the defines or add this to your platformio.ini:
```
build_flags =
    -DMS_LOGGERMODEM_DEBUG
    -DMS_SODAQ2GBEER6_DEBUG
    -DMS_SODAQ2GBEER6_DEBUG_DEEP
```
Your log will suddenly get really long with all of the AT commands for the modem.  I want to see that.

Also, are you seeing the light on your Bee go on and go to the "connected" blink?

**Comment by fisherba** [comment]
"name": "TinyGSM",
  "version": "0.7.9",

    https://github.com/EnviroDIY/ModularSensors.git#628fc03c731ab80a923a50b480f1963b68af51f2

GPRSBee7

RTC syncs. Response code is 201, but modem status and signal are still -9999. 

Deep debug attached. If you have tips for exporting this from Atom/PlatformIO, I'm all ears, because copy/paste is only allowed page by page as far as I can figure out. 

[modem_log_baf_20190529a.txt](https://github.com/EnviroDIY/ModularSensors/files/3233985/modem_log_baf_20190529a.txt)

**Comment by fisherba** [comment]
Also, my Bee blinks when connected.

**Comment by SRGDamia1** [comment]
Huh.  It looks like I just wasn't waiting long enough to get an AT response from the modem.  I have no idea why the R6 might respond faster than the R7, but I guess it does.  The R6 also responded more slowly than I'd expected it to based on the manual.  I increased the time-out for the GPRSBee in particular and the padding for all the modems.  Try again.

Also, turn on the deep debugging for the logger modem ```-DMS_LOGGERMODEM_DEBUG_DEEP``` or in LoggerModem.h.  That should give a better clue as to what's timing out.

[TeraTerm ](https://ttssh2.osdn.jp/index.html.en)is a decent serial port monitor/terminal emulator that you can use to log the output much more easily than the PIO MiniTerm in Atom or VSCode.  I've also tried RealTerm and a few others.

**Comment by fisherba** [comment]
Funny story... I've looked at a few terminal emulators, but they weren't MacOS friendly (including TeraTerm). Then I realized that I could use the Arduino IDE! It allows me to select all and paste the whole serial monitor log in one fell swoop. (In other words, build and upload in PlatformIO, monitor in ArduinoIDE.) The answer was right in front of me all along. I don't want to tell you how long it took to copy/paste all those pages... #facepalm

"name": "TinyGSM",
"version": "0.7.9",
GPRSBee7
```https://github.com/EnviroDIY/ModularSensors.git#7c87f7380dd4c757bc12cd33864ffc821187dccb```

The result with the latest commit is the same. We have logging to EnviroDIY, 201 response, but still -9999 on the modem variables. 

[modem_log_baf_20190530.txt](https://github.com/EnviroDIY/ModularSensors/files/3237930/modem_log_baf_20190530.txt)

**Comment by SRGDamia1** [comment]
Oh, it's actually that the status pin isn't coming on.  I increased that buffer (more).  Sorry.  Try again.

If that doesn't work, try setting your modem status pin to -1 and see what happens.

**Comment by fisherba** [comment]
@SRGDamia1, is there a new commit? The last one I see right now is from last night.

**Comment by SRGDamia1** [comment]
Oops, forgot to push.  Sorry!!

**Comment by fisherba** [comment]
[modem_log_baf_20190530b.txt](https://github.com/EnviroDIY/ModularSensors/files/3238813/modem_log_baf_20190530b.txt)

**Comment by SRGDamia1** [comment]
The R7's status pin must not be connected to the SIM800 the way it is on the R6.  In your code, set the status pin to -1 (```const int8_t modemStatusPin = -1;```)

**Comment by fisherba** [comment]
```const int8_t modemStatusPin = -1;``` worked! (Sorry I forgot to add that in for the last round.)

[modem_log_baf_20190530c.txt](https://github.com/EnviroDIY/ModularSensors/files/3238886/modem_log_baf_20190530c.txt)

**Comment by SRGDamia1** [comment]
Yay!  Now it would be very nice if we could get a schematic to let us know *why* the status pin wasn't working.  You didn't put the GPRSBee on top of one of the new LTE adapter boards, did you?  It's sitting right on the Mayfly, right?  Looking at it, does it look like there are any traces wired up to pin 12?  (That's the second from the bottom on the left when you're looking at it from the bottom where the sim card slot is.)

**Comment by SRGDamia1** [comment]
Since it's finally working, and it seems to have been the R7's fault the whole time, I'm going to merge this pull request and make a new issue for the R7.

**Comment by fisherba** [comment]
I don't see traces in that spot. Tonight I will look at a version 6 and I could test it with the LTE adaptor if you are curious. 

(Now that I can copy/paste in one fell swoop, sharing the debugging is so much happier.)

**Comment by aufdenkampe** [comment]
Here's a comparison of the two GPRSBee versions, with Rev. 6b on the left and Rev. 7b on the right.
They look quite different! It's discouraging that they only have documentation on rev. 6b at http://support.sodaq.com/sodaq-one/gprsbee/!

GPRSBee_r6-r7-compare_bottom

GPRSBee_r6-r7-compare_top

From my look, I would agree with Beth that Pin 12 (CTS for  power status) does not seem to be wired to anything on Rev. 7b. I'll do some testing.

**Comment by aufdenkampe** [comment]
This fixes #253! See https://github.com/EnviroDIY/ModularSensors/issues/253#issuecomment-497560686

**Pull request merged**
