### PR TITLE
Add Turner Cyclops support

### PR DESCRIPTION
**Pull request by SRGDamia1**

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Please add your changes to the change log!

**Comment by SRGDamia1** [comment]
And with this new sensor, the menu of *everything* can no longer fit on a Mayfly.  Now I have to get more creative about how to do the build tests.

**Comment by aufdenkampe** [comment]
@SRGDamia1, there are many sensors in our `menu-a-la-carte.ino` that we never really use anymore. I'm happy to suggest some to drop.

**Comment by SRGDamia1** [comment]
@aufdenkampe No, I don't want to drop anything.  By having *everything* the menu serves as both a build test and source of example snippets for every modem/sensor/publisher.

**Comment by neilh10** [comment]
Hey fascinating to see these fluorescence instruments.  Very nice.

**Pull request merged**
