### PR TITLE
Merge Develop to Release 0.22.5

### PR DESCRIPTION
**Pull request by aufdenkampe**
Most of this was developed in the *modems* branch and discussed and tested in #252 **Radically simplified modems in sketches by making a modem parent class**.

I think this is ready for prime time. What do you think @SRGDamia1, @fisherba and @neilh10?

### CODE REVIEW

**Comment by neilh10** [comment]
I've liked what I've seen- simplified modem interface.   I haven't had the chance to check or integrate it and I won't be able to do it till mid July so don't wait on me.  I'm on the road so only have basic tools with me.

**Comment by SRGDamia1** [comment]
I haven't tested it on anything other than the Mayfly yet - usually I at least test it on my Feather M0.  I have tested it on all of the modems I have [GPRSBee 6 (SIM800), GPRSBee 4 (SIM900), Itead Wee (ESP8266), DFRobot ESPBee (also ESP8266), Sodaq UBee SARA U201, XBee Wifi, XBee Cellular Transparent (3G, LTE-M, and LTE C1), XBee Bypass (3G and LTE-M), and a Sequans Monarch LTE-M] but the BG96, SIM7000, and UBee SARA R410 are untested and written based on manuals and conversations with @acgold.

**Comment by aufdenkampe** [comment]
@SRGDamia1, it makes sense that you might want to test it on the Feather M0 board first, before we release it. No rush. I'll probably start deploying stations from this code base this week, and will record my successes and issues as I do.

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'm no longer getting a printout of the JSON to send, as it sends to data.envirodiy.org. 

```

 \/---- Line Saved to SD Card ----\/
2019-06-04 15:16:00,57.354,24.27,75.69,96885.06,3461,1538,24.1875,75.54,-9999,-9999.00,4.154,-81,52



Sending data to data.envirodiy.org
-- Response Code --
201
------------------------------------------
```

Is this what you intended? I liked seeing that previously, because it helps me debug UUID issues, etc.

**Comment by aufdenkampe** [comment]
I discovered an odd bug related to older Mayfly version.

As mentioned in https://github.com/EnviroDIY/ModularSensors/issues/116#issuecomment-498863236 and below...
- With Mayfly v0.3, I was getting -9999 values for `RainCounterI2C` variables for the first round of logging, then it works after that. It always works in sensor testing mode.
- With Mayfly v0.5 and v0.5b, with the same code and compile `RainCounterI2C` variables work great, but the `RSSI` and `signalPercent` then give good values for the first round of logging, then -9999 values after that. It always works in sensor testing mode.

This is my sketch: https://github.com/LimnoTech/EnviroDIY_deployments/blob/f8b2b5737706aaa0541d724653f033b489c23f7e/deploy-HH/BassLakeV2/BassLakeV2.ino

```ini
; Using ModularSensors *develop* branch (v0.22.2) as of 2019-05-30: head, 75 commits ahead of master (v0.21.4)
    https://github.com/EnviroDIY/ModularSensors.git#3b9142315a7801b3bc595ef10ec79d6041df4093
```

**Comment by aufdenkampe** [comment]
I just tried a different sketch with the Mayfly v0.5b, and I didn't have the same issue as noted above in https://github.com/EnviroDIY/ModularSensors/pull/256#issuecomment-498899423. The only difference with that sketch is that modem variables were not last in the list.

https://github.com/LimnoTech/EnviroDIY_deployments/tree/c38ab608eafd827a8380967d0cc6f594fb937fe4/deploy-RVSMRTDC/DoEE_McF_RG

**Comment by aufdenkampe** [comment]
Update to https://github.com/EnviroDIY/ModularSensors/pull/256#issuecomment-498899423.

I let the `BassLakeV2.ino` sketch run overnight on a Mayfly v0.5 and other hardware, and after several hours the `RainCounterI2C` started logging -9999 values after working just fine for several hours. See https://monitormywatershed.org/sites/BassLakeWI/.

@SRGDamia1, any ideas on this? I'll try debugging mode for the sensor.

**Comment by fisherba** [comment]
@aufdenkampe, for what it's worth, the -9999's seem to correlate with lower voltage.

**Comment by SRGDamia1** [comment]
To see the full text printout, you need to turn on DataPublisherBase's debugging, or comment out lines 106 and 110 in dataPublisherBase.cpp.  That can be changed back to always print if you prefer.

**Comment by SRGDamia1** [comment]
The problems with the I2C rain sensor should not be in any way related to this pull request.  Let's keep that discussion on that issue.  This PR didn't change anything related to the way data is polled or received from that specific sensor or any sensor or variable in general.  There was a very minor fix to the logic of powering off a sensor, but based on your log, that's not the problem.

**Comment by aufdenkampe** [comment]
@SRGDamia1, it's good to know that the code developments for this release (and possibly the previous 0.21.x releases) are not very likely to have messed with the Variable Array. I had thought that it might, given that it seemed we had similar issues with the GPRSBee modem variables. I make sense that those might be unrelated.

I'll move all discussions of `RainCounterI2C` back to #116.

**Comment by aufdenkampe** [comment]
@SRGDamia1, have you been able to test this yet on the M0 boards? It would be great to release this!

**Comment by SRGDamia1** [comment]
I'm going to work on this today.

**Comment by SRGDamia1** [comment]
I've tested the SAMD stuff and rolled in the timezone fix so lets get this pulled and released!

**Comment by SRGDamia1** [comment]
I'll try to get to the release notes soon.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you! Once you do that, I'll also attend to the Zenodo stuff.

**Pull request merged**
