### PR TITLE
Base level build - but never outputs to console. Possibly constructor issue

### PR DESCRIPTION
**Pull request by neilh10**
This builds, but then the console never comes up.
I looked for simpler sensors - I tried similar with logging_to_MMW.ino - but it fails wtih 

Compiling .pio\build\mayfly\src\logging_to_MMW.ino.cpp.o
In file included from D:/usr/a/Documents/Arduino/envtmp/ModularSensors/examples/logging_to_MMW/src/logging_to_MMW.ino:145:0:
.pio\libdeps\mayfly\EnviroDIY_ModularSensors\src/sensors/BoschBME280.h:95:29: fatal error: Adafruit_BME280.h: No such file or directory

### CODE REVIEW

**Comment by SRGDamia1** [comment]
I'm fairly certain that moving the file into a examples/name/src/name.ino would not work appropriately with the Arudino IDE, or, as far as that goes, with the web page that presents examples on the PIatformIO library viewer (https://platformio.org/lib/show/1648/EnviroDIY_ModularSensors).

As I said, I don't like the convention of naming the examples and folders as such, but it is more-or-less the standard for Arduino libraries and no-one asked me.

**Comment by aufdenkampe** [comment]
I agree that we want to follow standard Arduino file path conventions.

**Comment by neilh10** [comment]
Well whatever you guys think. 

I think of "Arduino Coding" as simple tutorials that just work, and I was just trying it out, as I was running into problems elsewhere and wanted a quick check.

This was about logging_to_MMW.ino not working - the compiler puts it together, linker does its job, and it downloads, then kaput doesn't even come up.

I really appreciate there is so much work that has gone into the documentation and explanations, and it takes a lot of work to simplify it, so it just works.  
So as a community member just trying it out as I had failures elsewhere and wanted a baseline that could post to MMW.

**Comment by SRGDamia1** [comment]
Ok, sorry, so if the logging to MMW example isn't working, that's a problem.  I'll test it tomorrow.

But moving the program file to a different (non-standard) folder shouldn't fix an issue with the content of the program.  I've improved the directions for all of the examples explaining that a new project should be created and where to put the required ino and ini files.

**Comment by neilh10** [comment]
I appreciate the dynamic range of the tutorials - from newbie starting out in 
GettingStarted/GettingStarted.md
and that it looks to me that logging_to_MMW.ino should work. But it didn't when I last ran it . 

I followed your new instructions with PIO, Create a new PIO project "my_logging_to_MMW" specifying board Mayfly,  
copy in logging_to_MMW/platform.ini  and 
 src/logging_to_MMW.ino, 
delete main.cpp, build .....  and it builds - 
but I haven't got an available test system to try it (they are all busy). Will try it tomorrow.

Just an observation with your reference in the beginning of "Modify Examples"

```
- [menu_a_la_carte](https://github.com/EnviroDIY/ModularSensors/tree/master/examples/menu_a_la_carte)
    - This shows most of the functions of the library at once.
 It has code in it for every possible sensor and modem and for both AVR and SAMD boards.
It is also over 1500 lines long.
```

It is a very valuable reference. I certainly appreciate digging through all the sensors. 

Wouldn't it be better to stick this at the end of the examples, and let a newbie start with simple stuff, get good feedback with a toddle. 
Then when they are all excited about sensors :)  ..... they can start reading up on  menu_a_la_carte
 
Following the example,  and building menu_a_la_carte ...%~%...    pretty  impressive  ...%~%...    it just fits in memory. 
RAM:   [========= ]  89.3% (used 14631 bytes from 16384 bytes)
Flash: [==========]  98.2% (used 127726 bytes from 130048 bytes)

**Comment by neilh10** [comment]
I take it back its worked for me ...

Now running logging_to MMW.ino on Logger XXXXX

Using ModularSensors Library version 0.27.8
TinyGSM Library version 0.10.9

Logger timezone is set to UTC -5
RTC timezone is set to UTC
Current RTC time is: 2021-01-21T15:20:48-05:00
SampNum has a non-unique UUID!
BoschBME280Temp has a non-unique UUID!
BoschBME280Humidity has a non-unique UUID!
BoschBME280Pressure has a non-unique UUID!
BoschBME280Altitude has a non-unique UUID!
DS18Temp has a non-unique UUID!
Battery has a non-unique UUID!
BoardTemp has a non-unique UUID!
decibelMiliWatt has a non-unique UUID!
12345678-abcd-1234-ef00-1234567890ab -> SampNum
12345678-abcd-1234-ef00-1234567890ab -> BoschBME280Temp
12345678-abcd-1234-ef00-1234567890ab -> BoschBME280Humidity
12345678-abcd-1234-ef00-1234567890ab -> BoschBME280Pressure
12345678-abcd-1234-ef00-1234567890ab -> BoschBME280Altitude
12345678-abcd-1234-ef00-1234567890ab -> DS18Temp
12345678-abcd-1234-ef00-1234567890ab -> Battery
12345678-abcd-1234-ef00-1234567890ab -> BoardTemp
12345678-abcd-1234-ef00-1234567890ab -> decibelMiliWatt
12345678-abcd-1234-ef00-1234567890ab -> signalPercent

This logger has a variable array with 10 variables, of which 8 come from 4 sensors and 2 are calculated.
Sampling feature UUID is: 12345678-abcd-1234-ef00-1234567890ab
Logger portion of setup finished.

Setting up sensors...
Attempting to connect to the internet and synchronize RTC with NIST
This may take up to two minutes!
Could not wake modem for clock sync.
Putting modem to sleep
Setting up file on SD card
Data will be saved as XXXXX_2021-01-21.csv
Putting processor to sleep

**Comment by SRGDamia1** [comment]
I'm glad it's working!  I'm sorry, I still haven't tested it yet.

**Pull request closed without merging**
