### PR TITLE
Paleo wire

### PR DESCRIPTION
**Pull request by SRGDamia1**
Different form of software wire to increase compatibility

### CODE REVIEW

**Comment by SRGDamia1** [comment]
If this works for the PaleoTerra, I will likely re-write _all_ of the I2C sensors to allow similar input.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you! That would be really awesome! We'll test this soon.

**Comment by SRGDamia1** [comment]
While there's nothing "wrong" with this, it won't actually work.  The needed functions in the TwoWire class that is part of the Arduino core aren't virtual.  You can over-write the non-virtual functions if you directly call an object, but when you're calling a pointer it won't work.  (https://stackoverflow.com/questions/11067975/overriding-non-virtual-methods)  So you'll never be able to talk to the sensors by feeding a pointer to a software wire instance in the constructor because the hardware wire's functions will be called anyway.  The fact that Adafruit's libraries all allow a pointer to the Wire as input is only useful to someone using a non-standard core.

So, to allow software or hardware I2C interchangably, the software I2C library of interest would have to be a dependency, just like in the current PaleoTerraRedox branch.  Or we'd have to delve into CRTP or other tricks to correctly overwrite the non-virtual functions.

**Comment by SRGDamia1** [comment]
@aufdenkampe @fisherba @bschulz1701 
I've spent way, way too long fidling with this, only to come back to nearly exactly where you were before I started fiddling with it.  Testing with the I2C Atlas sensors I have, I could *not* get it to work with templates or pointers or any other way I could think of to support both hardware and software I2C.  The powers that be writing the Arduino core just didn't make the I2C class properly virtual.  In all the work-arounds I tried I kept having issues with object slicing and the communication just wasn't working.  So it's all the way back to making a software I2 library a dependency and using a build flag to note whether you're using hardware or software I2C.

The big differences between the branches:
- Using Testato's SoftwareWire instead of TodBot's (TodBot's I2C class isn't subclass of stream)
- To enable software wire, you must compile with the build flag ```-DMS_PALEOTERRA_SOFTWAREWIRE``` in your platformio.ini
    - You can't mix-and-match with one sensor using hardware I2C and another on software; it's all or nothing.
- If you use software wire, you'll get a build warning about possible undefined behavior.  Because the destructors are empty, this should be ok, but you'll see it.
- SAMD21's can't use software wire for anything
- SAMD21's now _can_ use a second hardware wire for nearly _all_ I2C devices
    - That is, a SERCOM could be turned into a Wire2 just as the code sets up Serial2 and Serial3 now.  The SAMD21's have 6 SERCOMs that can each be assigned to any of UART, SPI, or I2C.

**Comment by aufdenkampe** [comment]
I just talked to @fisherba, and she won't be able to re-test the head of this branch with actual paleoterra redox sensors, because she deployed them on June 27, after committing this code on June 26 at 10:30ish pm:
- https://github.com/LimnoTech/EnviroDIY_deployments/blob/master/deploy-BAF/WSP-01-2019/WSP-01-2019.ino
- https://github.com/LimnoTech/EnviroDIY_deployments/blob/master/deploy-BAF/WSP-02-2019/WSP-02-2019.ino

Although those sketches have a comment that they were compiled to commit https://github.com/EnviroDIY/ModularSensors/commit/87f3d67c0423014863a88f261c1b42a4240dcb35 done on June 24 just before the first commit in this PR, the two sketches also have `libraryVersion = "0.22.6"`, which happened June 25 with https://github.com/EnviroDIY/ModularSensors/pull/264/commits/02799c1f9451ed4940011a9537eb077e08dcdcb5.

Based on this, and my analysis of spit-diffs with different snapshots of `menu_a_la_carte.ino`, I'm convinced that Beth deployed using https://github.com/EnviroDIY/ModularSensors/commit/1e8a205d6c549b3340ac7323173885dced1872e1 that I committed to paleo wire in the evening of June 26.

Unfortunately these 11 commits since then have not been tested:
https://github.com/EnviroDIY/ModularSensors/commits/paleoWire/examples/menu_a_la_carte/menu_a_la_carte.ino

**Comment by aufdenkampe** [comment]
Given all of @SRGDamia1's work and testing on this, and the benefits of Testato's SoftwareWire instead of TodBot's, I think we should merge this into the `PaleoTerraRedox` branch, from where we can better evaluate the merge to develop.

**Pull request merged**
