### PR TITLE
PR for release v0.34.0

### PR DESCRIPTION
**Pull request by aufdenkampe**
@SRGDamia1, I think it might be time for a new release!

The `develop` branch is 79 commits ahead of `master` since v0.33.4 was released on June 8. These include a bunch of new features and fixes, such as:
- #416 
  - #418
- #420 
- #421 
  - #423
- and a ton of new bug-fixes by you.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Please add your changes to the change log!

**Comment by aufdenkampe** [comment]
@SRGDamia1, are you able to review and merge this PR?

It looks like folks are starting to build off the `develop` branch. See:
- https://github.com/EnviroDIY/YosemitechModbus/issues/32#issuecomment-1404061361

**Comment by SRGDamia1** [comment]
@aufdenkampe Would you please add some documentation for me? The check documentation action is failing because it expects to find a section in both the menu_a_la_carte.ino and the readme/walkthrough in that folder for every declared sensor class.

If you look at the [output](https://github.com/EnviroDIY/ModularSensors/actions/runs/4418443144) from the action that checks, for the documentation, it tells you that both the Yosemitech 700 and the Campbell RainVUE are missing the expected example code. You should be able to follow similar documentation examples from the other sensors to figure out what's missing.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for working on this today! I'm happy to add more documentation, and appreciate your pointers to where and how.

BTW, the formatting of the Doxygen pages seems to be wonky: https://envirodiy.github.io/ModularSensors/.  Hopefully we can fix that with this release.

**Comment by aufdenkampe** [comment]
@SRGDamia1, for that [last Action output](https://github.com/EnviroDIY/ModularSensors/actions/runs/4418443144/attempts/1#summary-11996719287), why is the test looking for `BUILD_SENSOR_CAMPBELL_RAIN_VUE10` when I have `BUILD_SENSOR_CAMPBELL_RAINVUE10`? What is wrong with my choice of spacing?

**Comment by SRGDamia1** [comment]
Doh. It's the camel-to-snake case sluggify. The mid-word capital messes it up.

**Review by SRGDamia1 — APPROVED** [review]

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for getting this PR to pass and for showing me all the places that I need to properly build the docs!

**Pull request merged**
