### PR TITLE
Modem tweek

### PR DESCRIPTION
**Pull request by SRGDamia1**
This doesn't add any features, but it should get the modem to run a little more smoothly by better integrating a modem master class.

This breaks backwards compatibility.. again.. (sorry)

Also, this is mostly dependent on changes I made in TinyGSM, so you **must** update that library!

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for pointing me to this! 
I'll try to do some testing in the next day or so, as I'm very keen build off this to get something working in the `lowPower` branch by the end of the week to address #163.

**Comment by gcutrell** [comment]
@SRGDamia1 To try and help with debugging I just built a simple program using your newest commit 8d06d36 after backing down the EnableInterrupt version I came across these errors in the void setup(); The program built without issues using EnviroDIY_ModularSensors@=0.11.6.  

C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino: In function 'void setup()':
C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:591:21: error: 'class LoggerEnviroDIY' has no me
mber named 'init'
C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:609:15: error: 'class loggerModem' has no member
 named 'setupModem'
C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:609:86: error: 'ModemSleepMode' was not declared

 in this scope
C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:621:39: error: no matching function for call to 
'LoggerEnviroDIY::attachModem(loggerModem*)'
C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:621:39: note: candidate is:
In file included from C:/Users/gcutrell/Documents/GitHub/EnviroDIY_deployments/deploy-Limno/AA_Demo-2/AnnArbor_Demo2.ino:55:0:
.piolibdeps\EnviroDIY_ModularSensors\src/LoggerEnviroDIY.h:35:10: note: void LoggerEnviroDIY::attachModem(loggerModem&)
void attachModem(loggerModem& modem);
^
.piolibdeps\EnviroDIY_ModularSensors\src/LoggerEnviroDIY.h:35:10: note:   no known conversion for argument 1 from 'loggerModem*' to 'loggerModem&'

**Comment by aufdenkampe** [comment]
@gcutrell, your `.ino` file should not compile against BOTH commit 8d06d36 and `EnviroDIY_ModularSensors@=0.11.6`, because @SRGDamia1 broke backward compatibility in this branch. Therefore the functions are different.

You'll thus need to rewrite your `.ino` file using the Examples in this branch here:
https://github.com/EnviroDIY/ModularSensors/tree/lowPower/examples

**Comment by gcutrell** [comment]
Thanks. I recall the breaking backward compatibility now.

**Comment by gcutrell** [comment]
@SRGDamia1 I have a program compiled against commit 8d06d36<8d06d36> running to log battery voltage to eniryodiy using a SM800H but the cell modular is not powered up (no blinking net light). I ran the new StreamDebugger and the only serial output are AT's. I have the TINY_GSM_MODEM_SIM800 defined. I'm assuming the power issue is the cause of 'This logger is tied to a unspecified modem for internet connectivity.' Everything else seems to be running OK.

**Comment by SRGDamia1** [comment]
I'm sorry!  You're running against "bleeding edge" code... and it's pretty bloody.  I've re-written the modem a couple of times trying to optimize its power use.  Can you try the most recent commit?

**Comment by SRGDamia1** [comment]
@gcutrell  - Just FYI, if you're running against commits in branches that I haven't submitted a pull request for, I won't even promise it will successfully compile and definitely won't promise it will work.

**Comment by SRGDamia1** [comment]
I'm closing this pull request for now.  I'll open another one once I'm more settled on the low power branch.

**Pull request closed without merging**
