### PR TITLE
Add support for Gropoint Profile Probe using Modbus

### PR DESCRIPTION
**Pull request by aufdenkampe**
The [GroPoint Profile GPLP-8 Eight-Segment Soil Moisture and Temperature Profiling Probe](https://www.gropoint.com/products/soil-sensors/gropoint-profile) can be purchased with optional capabilities to use the Modbus communication protocol, rather than the standard SDI-12.

This PR adds a wrapper for the eight-segment GPLP-8 model using Modbus communication.

It depends on the https://github.com/EnviroDIY/GroPointModbus library, which also only implements the eight-segment GPLP-8 model probe.

Both libraries could be very easily modified to support the GPLP-2, GPLP-3, GPLP-4, GPLP-5, and GPLP-6 models using Modbus.

This code has been well tested and could be merged to `develop` if CI tests pass.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Please add your changes to the change log!

**Comment by aufdenkampe** [comment]
@SRGDamia1, can you help me figure out what I need to fix to get the Documentation tests to pass?
This branch is fully working and tested on numerous deployed stations, many having multiple sensors, including from YosemiTech.

**Comment by SRGDamia1** [comment]
@aufdenkampe There were a couple of things tripping you up.  

- First was my function to "snake-ify" GroPoint resulted in "gro_point" not "gropoint" so it was looking for tags with that extra underscore. I fixed that in 0e5bb2c6d3fdd8e01f370f457180e5f402cb8a9c and 8097325cba824e500dfb2f20594f77f0e6f064f9
- Second, you created variables in the GroPoint sensor's h file but didn't use them in the menu snippet. Instead, in the menu snippet, you created new raw variables. So your example worked, but it didn't exemplify each class you created. I fixed that by making the variables for the GroPoint dependent on the variable number instead of using a definition for the order number like most sensors. Then I used those variables in the example. The code you have should still work fine, though. 
- Last, the Arduino CLI checks were failing because the continuous integration script wasn't installing the GroPoint library. I had to add the library in the two scripts that install dependencies (for the CLI and PIO).  I also.. er.. took the liberty of modifying your library and publishing it to both the Arduino and PlatformIO library registries.

**Comment by SRGDamia1** [comment]
Building the libraries with the Arduino CLI isn't expected to pass until the Arduino library registry is fully updated. From that repo, they say it should be "within a day's time."

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you so much for letting know what was tripping up GitHub Actions, and then fixing those issues!! I really appreciate it.

I also appreciate your modifications to my GroPoint variable classes and how to best use them in this use case where I create multiple instances of each. That's really helpful to see what you did with those, and I'm really happy that the example now shows that much cleaner approach to constructing the variable objects. Thanks!

And thanks for taking the initiatives to moving the GroPointModbus library into the PlatoformIO and Arduino library registries. I appreciate that.

**Pull request merged**
