### PR TITLE
Update master with Tally counter (wind) & PaleoTerraRedox

### PR DESCRIPTION
**Pull request by aufdenkampe**
Supporting #269, bringing in capabilities to use the NorthernWidget Tally device for analog "reed-switch" anemometers for wind speed.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, well, this PR is messed up. When I tried to use the GitHub's relatively new "resolve merge conflicts" button with PR#321 (updating develop from master), somehow it also automatically merged develop into master with this https://github.com/EnviroDIY/ModularSensors/commit/003b8238fd0298bfa3e1dd402d717eb79af49005.

Reverting didn't give me the opportunity for us to review my changes. However, it is still possible to see them with https://github.com/EnviroDIY/ModularSensors/commit/003b8238fd0298bfa3e1dd402d717eb79af49005.

@SRGDamia1, could you review the changed files in https://github.com/EnviroDIY/ModularSensors/commit/003b8238fd0298bfa3e1dd402d717eb79af49005 and let me know if this will work to merge into Master?

**Comment by aufdenkampe** [comment]
@SRGDamia1, also Travis is failing on a bunch of example files that I never edited, so I'm quite confused by this tangle I've created! Let me know if you would prefer for me cache my meaningful edits and the delete the develop branch to start from scratch. That could potentially be easier and more transparent.

**Comment by aufdenkampe** [comment]
@SRGDamia1, deleting my last 2 commits is another possibility for cleaning up the mess I made and helping make my PR more readable. Unfortunately, I don't feel confident enough with my Git commands to permanently erase commits on the master branch.

Here are the commits to erase from the master branch:
- 003b8238fd0298bfa3e1dd402d717eb79af49005
- f9afb5fa35a46a056ec52843e666443fa518c536

Is this something you might be able to do?

**Comment by SRGDamia1** [comment]
I'm looking at it now.  The GitHub merge tool always does the merge backwards of how I think it should be done.  I don't understand it.

**Comment by SRGDamia1** [comment]
I'm going to force-push my version of master and then re-do the merge,

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you! That did it. Thank you!

I would like to push these changes to master relatively soon. Are the Travis errors an issue?
Take a look at the changed files and let me know if I need to make additional modifications.

I made some edits to the `menu_a_la_carte.ino`, mostly to default the serial stream to `AltSoftSerial` and also to add in the statements in the Arduino loop to force the modbus pins low before sleep (and then re-begin when awake again). I want this in the example because so many of the people I work with use these statements. I might make it more efficient however, before committing to master, but want to test it first (hopefully this morning).

**Comment by SRGDamia1** [comment]
The travis failures aren't a huge problem right now, but I do want them to be fix.  I'll try to get it done by the end of the week.

**Comment by SRGDamia1** [comment]
Before then, please go through TallyCounterI2C.h and .cpp to add all the appropriate Doxygen comments.  You can use the AM2305 or the BME280 as an example.

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'm looking over your latest `menu_a_la_carte.ino`, and see this at line numbers 219-220:

```cpp
// The pin numbers here are for a Digi XBee with a Mayfly and LTE adapter
const int8_t modemVccPin    = A5;  // MCU pin controlling modem power
```

However, in the `logging_to_MMW.ino` and `DRWI_LTE.ino` examples, `modemVccPin    = -1`.

What's the recommendation for a Digi XBee LTE-M with an EnviroDIY LTEbee adapter?

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you for putting this on your TO DO this week. In the meanwhile, I'll add those Doxygen comments as you suggest.

**Comment by SRGDamia1** [comment]
The A5 pin only works if you've done some soldering. I think being able to power the modem down is great, but I don't intentionally change the example. It migrated in from my local testing program.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for reminding me of the Mayfly's SJ7 options described in https://github.com/EnviroDIY/LTEbee-Adapter/edit/master/README.md! 
It's good to know that you use that option successfully.

I'll tweak the example to the default and add URL to description of options.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for all your hard work on getting Paleoterra into develop! I really appreciate it.
Let me know what else I can do to support pulling this into Master.

It will be great to clean up develop and all pending feature branch. My next work plan is to work on a modem (i.e. [MultiTech mDot LoRa](https://www.multitech.com/brands/multiconnect-mdot)), and a new publishers (i.e. [Ubidots](https://ubidots.com)) that @gcutrell has working for some of his deployments. Then I would like to also develop a publisher to [Cisco's Actility IoT platform](https://www.actility.com).

**Comment by aufdenkampe** [comment]
@SRGDamia1, let me know if there is anything else I might do to help get this released.

**Comment by aufdenkampe** [comment]
@SRGDamia1, is there anything I might do to merge this PR? I'm not really sure how to get Travis-Ci checks to pass. Do I need to?

I would like release this code soon, and also move forward with releasing PR #324, as I have additional development to do this month.

Last, I noticed that the links are broken to individual files listed at https://envirodiy.github.io/ModularSensors/files.html. Hopefully that's a quick fix that could be included in the release, but I'm not sure how to do that either.

**Comment by aufdenkampe** [comment]
No worries. I definitely understand being swamped. Thanks for the update.

**Comment by SRGDamia1** [comment]
@aufdenkampe can the Tally event counter really be run without continuous power?  I see "big capacitor... " but I'm guessing that a few seconds of power every couple of minutes is not going to keep that cap charged.  Have you actually tested it?  Unless it's actually tested and really does work that way, there shouldn't be an option for power supply.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for doing this review and getting it all ready to release!

According to @bschulz1701, who designed the [Tally](https://github.com/NorthernWidget-Skunkworks/Project-Tally), the combination of ultra-low power (~5 uA) and the super capacitor can indeed let it run without power, once the capacitor is charged. Evidently, a few seconds of topping off the super capacitor every logging cycle is all it takes to keep it going. I should mention that I've never tried that myself (I'm vaguely remembering that the ones I used didn't have a super capacitor installed), but there is mention of testing it all here: https://github.com/NorthernWidget-Skunkworks/Project-Tally#power-consumption. 

That said, I'm OK with your changes to remove the power pin as an argument for the constructor.

**Comment by SRGDamia1** [comment]
Yeah.. that power consumption page mentions tests at 50% duty cycle.  But 5s every 5 minutes is less than 2% duty cycle.  

I'm reading up on what exactly a "super capacitor" is and its uses.  From what I'm reading, they're an up-and-coming thing, but a device that has very low steady power draw still seems to fall solidly in the "use a battery" category.  I'm not the engineer and I don't want to remove an option in code for something that does work, but I am going to put big warnings in the documentation that I don't think it's a good idea.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for doing that research on super capacitors and adding the extra documentation and warnings.

**Comment by SRGDamia1** [comment]
This PR has gotten rather out of hand....I should have been much more careful to work in branches as I fiddled with bits of the documentation and then pulled Neil's stuff in to a separate branch.  Since it's already this old and out of hand, I'll wait for @neilh10 to check my edits and Travis to pass and then I'll finally merge.

I'll probably create and pull another quickly after this as soon as I get our new InSitu RDO working.

**Comment by SRGDamia1** [comment]
Travis has changed its pricing plans a lot:  https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing.  I didn't realize it until I started looking in to why the job logs were so far backlogged - previously they'd always queued and run almost immediately after a push.  I haven't had time to look into what the pricing changes will mean for CI for this and our other repos.

**Comment by neilh10** [comment]
The changes all look inline with pulling them into your framework  - which is great. 
Thanks for catching some of the areas I missed from the orginal sensor source- always helpful to have fresh eyes on it.
I'm not sure which param you mean to be setable instead of a define. I've tried to be flexibile, and for somethings add defines as well as functions.  I guess its a project call but it would nice to be able to leave flexibility that if parm is unlikely to be changed to have it as a define that can be overridden. Maybe just my way of adding flexibility.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you so much for your hard work at getting this large PR to pass Travis (and for sleuthing the recent slow Travis testing) and also for continuing to build the really fantastic documentation system! I'm looking forward to having these 175 commits merged into master and released!

@neilh10, thanks for contributions to a new sensor and the other work that you have in the queue!

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for pushing this across the finish line!!

I presume it's time for an official release. Do you want to initiate that or should I?

**Comment by neilh10** [comment]
Hey good to see the merge.  A lot of work come together, thankyou @SRGDamia1  for keeping it moving.
I've still got a question about how "the community" can help in this process of "testing a release"  ~ especially the core infrastructure.  Its usually a challenge and can be distributed, but best to agree a process and what the test should be.

I make a stab at it for two areas that I'm interested in - Digi S6 WiFi(as a stability test bed) and Digi LTE CAT-M1  - but I do it from my fork as there doesn't appear to be any agreed "test"

**Comment by aufdenkampe** [comment]
@SRGDamia1, the code documentation at https://envirodiy.github.io/ModularSensors/index.html still says v0.25.0.
Where do we need to update that? Let's make sure to do it before we issue the release.

**Comment by neilh10** [comment]
I stepped into  https://envirodiy.github.io/ModularSensors/getting_started.html and its 404
seems like it is https://github.com/EnviroDIY/ModularSensors/wiki/Getting-Started

**Comment by SRGDamia1** [comment]
oops.. I forgot to update all of the links correctly!  The getting started page is now here: https://envirodiy.github.io/ModularSensors/page_getting_started.html

At this point, the wiki is mostly"deprecated" in favor of the github pages. I haven't removed it yet because there are still bits there I haven't moved into the doxygen docs and I'm using it as a storage for a bunch of the datasheets I want to keep online but not in the main repo.

@aufdenkampe where are you seeing the version number in the docs?  Did you look at the docs before or after Travis re-generated them?  (That happened ages after the PR was merged... Travis is many hours behind all the time now.)  Can you put in a screen shot?

What do you think of the style changes for the docs?

**Comment by aufdenkampe** [comment]
@SRGDamia1, woah! The style changes on the docs are impressive! Nice job!

This morning was looking at an version of the Docs before the styling changes were fully turned on, so I think the version number issue has been resolved. I don't see the version number anywhere (but it might be nice to include somewhere.

The one styling change I might suggest is to somehow enhance the contrast of the code snippets and code blocks. The font is very thin, so the colors are subtle and all of it is hard to read on the grey background.

I also find that I'm missing the navigation side-bar. That was handy when drilling in on details.

Last, are the class structure diagrams still available? I found those useful.

Just found a broken link: https://envirodiy.github.io/ModularSensors/_digi_x_bee_8cpp.html 

Generally, the look and feel is great. Thanks for this major update!

**Pull request merged**
