### PR TITLE
Added ThingSpeak support

### PR DESCRIPTION
**Pull request by SRGDamia1**
Attach the modem now to a logger

Made another abstract class for a dataSender that registers to a logger to send data to a webservice.  EnviroDIY and ThingSpeak are now subclasses of dataSenders *NOT* of loggers.

### CODE REVIEW

**Comment by neilh10** [comment]
Wow Fantastic.   I pulled it into my environment, for platformio.ini  I added line to make it find the file 

src_dir = .

    https://github.com/EnviroDIY/ModularSensors.git#thinkSpeak

and it built OK.

I added the thingSpeak keys. And created some fields. I've used it before. 
However its not being presented on thingspeak. 
The readme.md is a good guide, but doesn't actually give an example of what the field needs to be. 
    new ProcessorStats_Batt(&mayfly, "field1"),
    new MaximDS3231_Temp(&ds3231, "field2"),

The terminal info lists that it has worked, but not what the http response is

<list begin>
Data will be saved as SL099_2018-12-19.csv
Push button on pin 21 at any time to enter sensor testing mode.
Logger setup finished!
------------------------------------------

Battery: 4.59
Battery: 4.59
Battery: 4.59
Battery: 4.59
Battery: 4.59
------------------------------------------
Successfully connected to SD Card with card/slave select on pin 12

 \/---- Line Saved to SD Card ----\/
2018-12-19 00:05:00,4.382,22.25


------------------------------------------

Battery: 4.59
</list>
I guess I need to enable some debugging.

**Comment by SRGDamia1** [comment]
This is using the ThingSpeak MQTT endpoint, not HTTP/REST.  There is no HTTP response code.  You can see if the MQTT "publish" was successful, but a successful publish doesn't necessarily mean that the data actually made it to your channel.  There's not any checking of that kind in the server's response to the publish, and I'm not attempting to read the channel to see if new data indeed arrived.

The data is sent to the fields assigned to your channel in exactly the order they are in your variable list.  You don't need to label them as "FieldX" and any label like that you do put in will be ignored.  This also makes no attempt to create a field; it has to already exist in your channel.  I updated the ReadMe a bit to make that a little clearer.

**Comment by SRGDamia1** [comment]
Use the develop branch now to test this.

**Comment by neilh10** [comment]
I guess one of the issues is that its a challenge to see the flow - 
It would be nice to be able to easily specify a level of debugging. In some of my modules I'm implementing a way of enabling debugging from platforimio.ini
eg
;-DLoggerBase_DBG
then in LoggerBase.h I have something that I can enable permantely or in platformio.ini
// Debugging Statement
//#define LoggerBase_DBG 1
#ifdef LoggerBase_DBG
  #define DEBUGGING_SERIAL_OUTPUT Serial
#endif //LoggerBase_DBG

 Debugging is not really a big deal in an environment already setup - its just extra work to do in a new instance, and even more challenging for a newbie. 
I find I have to copy it from logging_to_xxx\ .piolibdeps\EnviroDIY_ModularSensors\src 
into 
logging_to_xxx\lib\ModularSensors\src
No big deal really.

Great to see ThingSpeak MQTT.  Hope to get back to it later today, it might be that that my Xbee WiFi  needs reinitialzing or something.

**Comment by SRGDamia1** [comment]
PlatformIO really isn't set up to work with a library in your source directory.  It's intended that all of the libraries be installed properly in one of you library folders and then your source directory just hold your single "main" program.  You have to kind-of contort your platformio.ini to build an example for a library that's in the src directory.  But it does work fine if you set it up right.  

All of those debugging statements were never intended for newbies or typical library users.  They are for looking for coding errors.   Some of them print out really gory detail that you definitely don't want to see except on special occasions.  I don't quite understand what you're copying or why to get the debugging to work.  Just uncomment the line with the define in the h/cpp pair you want to debug and then rebuild.  If it doesn't appear, try running a clean and then rebuild to force it to do a complete recompile.  I've found it to work best to only try debugging one thing at a time, and that's it's generally more of a pain to try to re-set build flags in the ini than to just change one line in the library source.  PlatformIO tries to avoid recompiling everything every time - it archives the compiled sections.  If you only change one line in one file to turn on debugging, it usually smartly only compiles only that file.  If you change a universal build flag in your platformio.ini it *has* to recompile everything.  Depending on the speed of your computer, you probably want to avoid that.

**Comment by SRGDamia1** [comment]
Also, I added better text in the ReadMe's for the examples on how to set up a new project in PlatformIO (Atom/VSCode).  See: https://github.com/EnviroDIY/ModularSensors/tree/develop/examples/logging_to_EnviroDIY

**Comment by neilh10** [comment]
I guess that was why I was asking in another issue what the best way of setting up ModularSensors for development is?. 

I assume from the "Fork it" comment on the main page you are open to other programmers to contribute -:) - possibly debug issues -   so somebody is a newbie to Mayfly but has programming experience and is prepared to contribute.?

I'm happy to make it work the best way I can  :)  - but was just noting some places might help to make it easier to pick up on.

**Comment by SRGDamia1** [comment]
I'm sorry, my goal in all of the documentation is to make it as easy and clear as possible for users/testers.  I'm really *hoping* there are and will be many more users than developers.  I'm afraid to have two sets of instructions (users vs developers) on how to set up PlatformIO because most environmental scientist types who I'm hoping will use this are very much unfamiliar with coding and GitHub in general and I want it to be very clear for them what they should do.

I'll add something to the Wiki about a set-up for development.

**Comment by neilh10** [comment]
Hi Sara,
Logging_to_ThingSpeak.ino as on develop branch is not working for me.

 I'm just wondering was it tested with Xbee WiFi - thats what I'm using with a network SSID and no pwd.
For Logging_to_ThingSpeak.ino I can't see where the Xbee is being initialized as in logging_to_EnviroDIY.ino  - though in my own  neilh10/ModularSensors fork I found for reliability I needed to modify the way  logging_to_EnviroDIY.ino initializes .

I've pulled in the develop branch, and with Logging_to_ThingSpeak.ino modified to make it compile in my environment, Enabled a few debug - and it looks like its not configuring the Xbee  WiFi - but I need to dig in deeper to figure it out. Any suggestions ?

[platformio]
description = ModularSensors example sending data to ThingSpeak
src_dir = .

[env:mayfly]
board = mayfly
platform = atmelavr
framework = arduino
upload_port = COM10
lib_ldf_mode = deep+
lib_ignore = RTCZero
build_flags =
    -DSDI12_EXTERNAL_PCINT
    -DMQTT_MAX_PACKET_SIZE=240
lib_deps =
    ;EnviroDIY_ModularSensors@=0.19.0
;  ^^ Use this when working from an official release of the library
    https://github.com/EnviroDIY/ModularSensors.git#develop

 \/---- Line Saved to SD Card ----\/
2018-12-20 13:10:00,-0.0109,16.39,4.518,19.75


  Connecting to the Internet...
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
AT
  Could not connect to the internet!
AT+WAKEUPGPIO=1,13,0
AT+SLEEP=1
------------------------------------------

Current Unix Timestamp: 1545311460
Logging interval in seconds: 120

**Comment by SRGDamia1** [comment]
The example is set up for an ESP8266.  (I decided to pick one instead of having them all there.)  You have to change all the modem code back to that for an XBee.

**Comment by SRGDamia1** [comment]
I created the page with suggestions on setting up for developers:  https://github.com/EnviroDIY/ModularSensors/wiki/Developer-Setup

**Comment by neilh10** [comment]
Wow - thanks for the developer setup. It is a lot more complicated than my basic setup, so will work through all the reasons. Added it to  https://github.com/EnviroDIY/ModularSensors/issues/205


OK I get it. logging_to_ThingSpeak.ino #65 says
// Select your modem chip, comment out all of the others
#define TINY_GSM_MODEM_ESP8266  // Select for an ESP8266 
and I need to paste (all the options don't exists)
#define TINY_GSM_MODEM_XBEE  // Select for Digi brand WiFi or Cellular XBee's

Being a hardware engineer I can now see that the ESP8266 can plug into J14. Very nice.

But then I also need to be able to put all the Xbee setup in there as well?. So I really need "developer skills" to be able to switch between WiFi comms devices.

Just wondering, since there are a lot of options couldn't all the visible user options be prioritized in the beginning of the file defined right up at the top,  or possibly as you suggested earlier a modularSensors_cfg.h
I know you have a lot of different examples file which is a lot of work - but wouldn't it simplify it if a modularSensor_cfg.h could be switched between the directories and that would take all the complex configuration with it.
Then as a "user" I would only have to know that I could move the modularSensors_cfg.h to take my environment with me. Well at least a thought :)
(The value of Xbee WiFi to me is that for some options I can add an external higher gain antenna and go longer distances.)

**Comment by neilh10** [comment]
Another thought - I guess its easy to throw out ideas - possibly simplifying  for "users" if the different communication methods (dataSender) be described as publishers (MQTT terminology) and then there be a compile option that defines a specific publisher. 
That way the effort of maintain multiple examples is minimized - there is one standardized framework  to teach of publishing ...... and an example "comms_to_cloud" instead of multiple "logging_to_XXXX"
The MQTT terminology also has a concept of subscription - for future extensions.

**Comment by SRGDamia1** [comment]
Basically every single line of the examples is a user setting. The library tries to handle everything that didn't need to be set by the user. I decided to dramatically simplify and sorten all the examples by keeping in only settings for one modem and no non-mandatory sensors, but even before I cropped them, essentially every line was a user setting that the individual user would have to change.

The wake and sleep functions are required input for the modems because they're extremely variable. Just saying "XBee" or "Sim800" would not be enough for the library to know how to wake or sleep the modem. The Digi brand is much more consistent than any other, but even then disconnected on sleep isn't the only option. I'd tried to have the library manage all the wake and sleep but it got to the point that even just for the modem chips on my desk I would need as many lines of code to tell the library the modem configuration as I would to just write out the sleep function in the main program.

**Comment by neilh10** [comment]
A comment on cheap Esp8266 with embedded unstated gain on the antenna (though usually 3db) - it needs u.fl or RPSMA. Typical WiFi is designed for a building reach.  2,4Ghz gets severely attenuated by water --eg plant leaves.  For an outdoor transmission 2.4GHz really needs to be boosted - I tie it in with an ENH202 Wireless Bridge  and an antenna on the mayfly side which needs the u.fl or RPSMA  connector which enables a higher gain antenna.

**Pull request merged**
