### PR TITLE
Time to merge Paleoterra redox into develop?

### PR DESCRIPTION
**Pull request by aufdenkampe**
It would be great to get this merged so that we don't need to manage it as a separate branch.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Does it still need to be dependent on a software i2c implementation?  Can that be changed?

**Comment by aufdenkampe** [comment]
@fisherba and @bschulz1701 can answer best, but my understanding is that for the initial implementation, all the shipped active redox sensors had the same I2C address (the default), because we weren't aware that those could not be changed by the user. So https://github.com/todbot/SoftI2CMaster is required to deploy more than one of those (at different depths) on the same Mayfly.

I think @fisherba now has some active redox sensors with different I2C addresses, so those don't require `SoftI2CMaster`.

**Comment by SRGDamia1** [comment]
Does the Testato software i2C library work on these:  https://github.com/Testato/SoftwareWire/blob/master/SoftwareWire.h?  Unlike most of the other software i2c libraries, this one actually inherits from the standard wire so you can write a sensor that calls for the i2c stream in the constructor and then feed it either this SoftwareWire instance or have it default to the hardware wire in your sketch.  That's just what we're doing for the various serial streams (ie, for the modem or the maxbotix).  Using it would eliminate the issues with non-AVR compatibility very nicely.

**Comment by aufdenkampe** [comment]
@SRGDamia1, that is a great idea! Thanks!

I discussed this with @fisherba a bit, and she's going to test the current head of this branch with hardware I2C later this week (she doesn't have the need for SoftI2C with the stations that she is deploying this week). While she's doing that, I might try out the SoftwareWire library you suggested.

Either way, let's hold off on this merge to develop until after we've issued Release 0.22.5 with #256.

**Comment by aufdenkampe** [comment]
@SRGDamia1 describes some important points describing the change to Testato's SoftwareWire (I2C) instead of TodBot's, and some general points regarding SoftwareWire in https://github.com/EnviroDIY/ModularSensors/pull/264#issuecomment-511046691.

I point out the latest tests by @fisherba of this in https://github.com/EnviroDIY/ModularSensors/pull/264#issuecomment-518878450, which were only using hardware I2C for redox sensors and also not using the code at the head of this branch.

I think that it might be wise to test this further before merging into develop.

**Comment by SRGDamia1** [comment]
@aufdenkampe  I am working on this merge right now!  Please do not make *any* changes on this branch until I have pushed my work.  (It's a messy merge so it will take me some time to clean it.)

**Comment by aufdenkampe** [comment]
@SRGDamia1, sounds good. I'll leave this Paleoterra redox branch all to you!

**Comment by SRGDamia1** [comment]
Done

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks!

**Pull request merged**
