### PR TITLE
Merge `develop` v0.23.5 into master, for release

### PR DESCRIPTION
**Pull request by aufdenkampe**
Minor changes prior to a release, mostly to address #277.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, Thanks for reviewing this and adding those changes. Do you need to do more Travis stuff before we merge to Master? 

I haven't quite redone all the examples yet to use the Digi LTE-M Transparent mode, so I probably wouldn't want to merge or release until then anyways.

**Comment by neilh10** [comment]
Great to see compile level modemPhy options menu_a_la_carte.ino/develop.
I'm trying a test with Digi WiFi S6B . I've added to platformio.inio 
-DMS_BUILD_TESTING     -DMS_BUILD_TEST_XBEE_WIFI 
and in menu_a_la_carte.ino copied it to src/menu_a_la_carte.ino (otherwise platformio doesn't find it) 
 added my open test SSID network definition and download to a Mayfly 0.5b with the S6B.
Unfortunately its not connecting to my WiFi - I have AT level trace from my working system (on same hw) so checking it out.
I have it working on my fork ok, (0.23.2) and use WiFi as a low cost reference.
Is it useful if I test develop :"0.23.5" on a  WiFi S6B?

**Comment by SRGDamia1** [comment]
@neilh10 I think any extra testing would be good, though there shouldn't be too many changes.

I decided to add the flags because I wanted a better way to test all the possible configurations to make sure things would work for all of them (or, well, at least compile).  Travis-ci really is wonderful for that.

**Comment by neilh10** [comment]
Thankyou thankyou - anything to make it easier for testing on the releases. I always like to organize  a "reference standard system" that makes it easy to regression test.   If regression testing isn't easy, I've found it doesn't get to be done :( 
I'm trying to look at regression testing off develop/0.23.5  now - though have some juggling (just processed 2*U30with dual kellers/20mA from a field site and in 45mins going to a LoRa users group this evening!)

**Comment by SRGDamia1** [comment]
I wish the code had proper unit testing built in.  It's now such a behemoth that going back and implementing tests would be very time consuming.

**Comment by neilh10** [comment]
IMHO embedded testing is always small system regression testing, and system behaviour is more visible. The hardware units and software are closely tied together. However as a system, some repeated behaviours can effectively regression test the whole system.
 I think of embedded regression unit testing  as enabling debug flags to be able to verify that unit if the system behaviour is strange.
Oh well - got a small merge on WiFi  - downloaded,, its waking every minute,  but now for some reason the 5minute logging interval isn;t taking effect. Will leave it running and gotta go, so will look at my system later.

**Comment by neilh10** [comment]
So it failed. Its failing on the 5min - ran for a couple of hours - 1 min wake up ok. but no 5min poll.
I suspect the refactoring white space has changed something.

Summarizing  - I have a working environment on my own fork based on 0.23.2 
So test the latest changes and provide a reference sandbox for a PR; I created a new Documents/Arduino/enviroDIY sandbox to build "develop"
https://github.com/EnviroDIY/ModularSensors/tree/master/examples/menu_a_la_carte menu_a_la_carte.ino  with Digi WiFi S6B . 
Took me about an hour to setup and 1st test download - and simplifying this is what I did
from develop created a branch dvlp_local 
I copied menu_a_la_carte.ino  to src/menu_a_la_carte.ino
and added to  platformio.ini 
src_filter =  +<*> 
    +<../../../src>  +<../../../src/sensors> +<../../../src/publishers> +<../../../src/modems>

build_flags =
    -DMS_BUILD_TESTING 
    -DMS_BUILD_TEST_XBEE_WIFI
    -I../../src ; .h For easy debug
    -DMS_LOGGERMODEM_DEBUG
    -DMS_LOGGERMODEM_DEBUG_DEEP
    -DMS_LOGGERBASE_DEBUG
    -DMS_DATAPUBLISHERBASE_DEBUG
    -DMS_ENVIRODIYPUBLISHER_DEBUG
    -DMS_DIGIXBEEWIFI_DEBUG
    -DMS_DIGIXBEEWIFI_DEBUG_DEEP
    -DMS_DIGIXBEECELLULARTRANSPARENT_DEBUG
    -DMS_DIGIXBEECELLULARTRANSPARENT_DEBUG_DEEP
    -DMS_DIGIXBEE_DEBUG

Downloading to Mayfly 0.5b, it ran but failed to connect to my open test network - reason unknown.
Turns out platformio was pointing at stream "master" 
I changed platformio to "develop" - deleted .pio/.../EnviroDIY_ModularSensors
and rebuilt and downloaded - and failed.

The challenge is in comparing environments,  the white space changes make it difficult to track real intended changes. What I do with refactoring, is save it up, and then do it on a release that has no other functional changes, so regression testing is easy.

I might if I get the chance  git backout out the white space changes and see what difference it makes - i've got a few things I'm juggling today.

**Comment by neilh10** [comment]
Well I'm not sure whether to post this, so ignore if its not useful. 

I pulled in the above changes, and building with reference to menu_a_la_carte.ino with Digi WiFi S6B  it runs and when the 5minutes expires it detects a "Time to Log!" - fantastic now works. 
But then freezes !

```
 ... zzzZZ Processor is now awake! <--LoggerBase
 Current Unix Timestamp: 1567619700 -> 2019-09-04T17:55:00-05:00 <--LoggerBase
 Logging interval in seconds: 300 <--LoggerBase
 Mod of Logging Interval: 0 <--LoggerBase
 Time marked at (unix): 1567619700 <--LoggerBase
 Time to log! <--LoggerBase
 ------------------------------------------
 Power to Digi XBee Wi-Fi is not controlled by this library. <--LoggerModem
 Running a complete sensor update... <--LoggerBase
```
(FREEZES no more activity)

So I've never tried to check the 'develop' with this method - build a test src/menu_a_la_carte.ino 
Since its an "example"  seems that since it includes so many sensors, it may not be a valid test setup. 

If there is a valid test setup with an Xbee WiFi that I can "regression" test "develop", with simple changes, be happy to try it out.

**Comment by SRGDamia1** [comment]
@neilh10 - there is definitely something wrong with the WiFi XBee, but I can't figure out what it is that I changed that made it stop working.  I have it correctly sending data, but it's not getting the signal strength and it's not talking to NIST.  It's locked up for me, but not in a consistent spot.  Go figure - I've finally got the cellular bees talking well to NIST.

For now, I'm going to pull this to master because we have a workshop coming up and I want everything to be on the main branch.

I'll ope

**Comment by aufdenkampe** [comment]
@SRGDamia1 and @neilh10, thanks for all your hard work in testing and refining this release. It'll be great to get this out the door as a new stable baseline.

@neilh10, are you using PlatformIO? 

I've worked out a workflow using PlatformIO that has made it quite easy to regression test/deploy any branch or past commit, at any time.  I do this in a separate PlatformIO "project" with a `platformio.ini` file that has a huge list of different development points, such as this:

```ini
; Using ModularSensors *develop* branch (v0.22.2) as of 2019-05-30: head, 75 commits ahead of master (v0.21.4)
;    https://github.com/EnviroDIY/ModularSensors.git#3b9142315a7801b3bc595ef10ec79d6041df4093
; Using ModularSensors *develop* branch (v0.22.2) as of 2019-06-05: head, 76 commits ahead of master (v0.21.4)
;    https://github.com/EnviroDIY/ModularSensors.git#a6e0270d63ba1d5ff056bdbea0596e23a574c29d

; Using ModularSensors *develop* branch (v0.22.4) as of 2019-06-24: head, 81 commits ahead of master (v0.21.4)
;    https://github.com/EnviroDIY/ModularSensors.git#c2e2e71f793a3a61adfa9f1a4ad6ba6a255a6e18
; Using ModularSensors *PaleoTerraRedox* branch (v0.22.4) as of 2019-06-24: head, 125 commits ahead of master (v0.21.4)
;    https://github.com/EnviroDIY/ModularSensors.git#87f3d67c0423014863a88f261c1b42a4240dcb35

;Using ModularSensors *paleoWire* branch as of June 26, 2019, synced to Master v0.22.6
;    https://github.com/EnviroDIY/ModularSensors.git#1e8a205d6c549b3340ac7323173885dced1872e1

    ; EnviroDIY_ModularSensors@=0.23.3

; Using ModularSensors *MeterTeros11* branch (v0.23.5) as of 2019-08-28: head, 7 commits ahead of master (v0.23.4)
    ; https://github.com/EnviroDIY/ModularSensors.git#0946ee72dae38b852b6761769c197a8dc6986bba

; Using ModularSensors *develop* branch (v0.23.5) as of 2019-08-29: head, 15 commits ahead of master (v0.23.4)
    https://github.com/EnviroDIY/ModularSensors.git#e09df0da8058c72bba8312b934123227360960e0
```

For every deployment that I do, I keep track of exactly which commit I built it against. I"m always extremely specific, to allow me to reproduce every deployment.

This is a slightly different workflow than developing within the ModularSensors repo itself, which I only use when testing new code *before* I make a commit.

I'm guessing that there is a git command that would allow reversion of the active branch within my ModularSensors to any previous commit, but I haven't tried that yet.

**Comment by neilh10** [comment]
Hi Anthony
I'd be happy to try for an easy way of helping with regression testing.  
Something referencing the stream develop, that could have a "git pull" with platformio setup for specific debug options and then press the build & download .....
The output debug script then can be easyly compared on different runs, and possibly even automated.

I'm using PIO(PlatformIO) on VSC(Visual Studio) and opening a folder to do a build. (Got the hang of Eclipse projects, but haven't put the time into the difference between VSC folders and projects).

For my own forked git,  I setup up development with its own folder
.Documents\Arduino\env03\ModularSensors\a\tu_mon\platformio.ini
and then in platformio.ini
    https://github.com/neilh10/ModularSensors#rel1_dvlp1m
It mostly works for me, and I can easyly switch between Mayfly and ARM.

For stream "develop" trying to build a Xbee WiFi/Mayfly for instance for ModularSensors/examples/menu_a_la_carte
I can setup a directory (disk space is soooo cheap nowdays) 
.Documents\Arduino\enviroDIY\ModularSensors\examples\menu_a_la_carte
but then I have to make a whole lot of mods to be able to build and download anything.

So an easy duplicatable regression test is out the window. Its not standard.
Not a problem really for a development environment.... but not for regression testing ...

Of course "menu_a_la_carte.ino" is meant as an example - so its not a good reference either. 

I think its pretty easy to create a regression test  - but its just whether its thought to be useful.  
I find it painful having to spend an hour each time making mods and tinkering to just get  it going (probably because I don't have a perfect memory for what worked last time in this configuration).
 
My past project/team experience, where I defined disparate testing across different geographical regions (ie not sitting down at same test station for developers)  was to define a realistic standard reference "regression" test station. (a specific complex new product). 
 This includes build method and hardware. Of course the reality is ModularSensors has a lot of different options.

I guess I'm checking in, would a regression test station that I can do based on Xbee WiFi/S6 be useful. It may not be a standard deployment,  but can do a speeded up regression test for everything except target instruments and specific comms methods. For me it doesn't have a comms bill if something goes wrong.

My suggestion would be to modify "menu_a_la_carte.info" to create testable builds (not just compilable options) ... could be something like
ModularSensors\test\menu_a_la_carte 

but would that be useful for the overall project.

**Comment by SRGDamia1** [comment]
I guess I'm not entirely sure what you mean by regression test in this case.  I generally run something similar to the menu example in my development testing, but I don't have it nicely formalized or automated. As a rule, I'd say more testing is better, though.  I understand that your merge and test set up is much trickier than Anthony's because your fork is more heavily modified.

**Comment by neilh10** [comment]
For what  I would call a Best Practices for embedded Regression  Testing (its a field I've been part of in the commercial world for 30yrs+ ) , is to define test system setup, and with expected functionality note the expected result.  
In this case reliably build & run the proposed release code  - the "regression test" on this system as part of each release cycle. In this case I'm suggesting  case an XBEE WiFi S6/Mayfly 0.5b with a standard set of sensors. 
By logs also include
`
---Boot. Build date: Aug 26 2019 12:45:38 src\tu_mon.cpp rel1_dvlp1m   
Mayfly v0.5b Ram available:10767
Good BatV=4.64
Using ModularSensors Library version 0.23.4
`
What I can't judge as I'm not part of the project, would this configuration be useful code coverage, for your project goals. I'm guessing your ideal target test system is a cell phone (3G moving to LTE). But the cell phone is more complex and possibly having the Xbee WiFi is going to show more stability except for the comms section.

In favour of the Xbee, its easier and low cost to setup - and I'm volunteering to run it.  I would keep logs of the debug output and start to compare them if things went wrong
The sensor functionality could be as broad as possible, Mayfly board temperature, and a large set of passive sensors (that aren't used) but initialize. For this past release the Xbee WiFi has more sensors.
(sorry I started this reply two hrs ago, and what with interruptions just getting to press send now)

**Pull request merged**
