### PR TITLE
Object initialization

### PR DESCRIPTION
**Pull request by SRGDamia1**

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'ld like to second @neilh10's appreciation. The level of attention and care you have been putting into making this library as stable as possible is extremely valuable. Others are noticing, and the result is that ModularSensors is becoming an exceptional body of work that is about to become one of the main open-source libraries for environmental IoT. Thank you!

**Comment by neilh10** [comment]
Hello @SRGDamia1, I'm having to revisit this to try and understand some issues I'm coming across 
I like your description above  .. but you have MS_DBG called in the constructors, and that is typically before the SerialXX is initialized.     
This is causing me failures with the ARM SAMD21 env with MS_DBG enabled. However seems to get a pass in AVR Mega1284!!

So with MS_DBG enabled for LoggerBase on ARM this fails and never starts     
Logger dataLogger(LoggerID, loggingInterval, sdCardPin, wakePin, &varArray);
If I comment out all MS_DBG in the constructors then it initializes . 
(I'm integrating Autonomo so its some new areas and for whatever reason Autonomo arduino framework has a small output buffer of 128bytes v feather of 256bytes - but trying not to get into the rabbit hole of updating arduino framework yet)

From the way the constructor is written it seems like this would work (and fits with your description)
Logger  *dataLogger;
xxxx
setup() {
Serial.begin(xx)
xxx
*dataLogger = new Logger;  //supports MS_DBG
}
however  I don't see that type of initialization anywhere.

So just curious as to what was working for you in the MS_DBG in constructors and direction you expect to take.    
thanks

**Comment by SRGDamia1** [comment]
There really shouldn't be any debugging statements in the constructors - like you said they could be run before the serial port is initialized.  Any debug statements left over in constructors are from when I was playing with the orders in which I was creating the objects to make sure things were all being created and linked in the orders I wanted.  They should just be commented out.

**Comment by neilh10** [comment]
Great thanks.

**Comment by neilh10** [comment]
Hi @SRGDamia1   Just any FYI - there is still MS_DBG in the LoggerBase:: as it calls other functions that do MS_DBG. 
I haven't yet worked through constructors in other classes yet, but thought I'd mention these 

Logger::Logger(const char *loggerID, uint16_t loggingIntervalMinutes,
               int8_t SDCardSSPin, int8_t mcuWakePin,
               VariableArray *inputArray)
{
    // Set parameters from constructor
    setLoggerID(loggerID);
    setLoggingInterval(loggingIntervalMinutes);
    setVariableArray(inputArray);



// Sets the logger ID
void Logger::setLoggerID(const char *loggerID)
{
    _loggerID = loggerID;
    MS_DBG(F("Logger ID is:"), _loggerID);
}

**Comment by neilh10** [comment]
So it turns out long constructor chains discussion is relevant - with more MS_DBG
Logger dataLogger(
Logger::logger - calls a number of foo() as above
then 
EnviroDIYPublisher EnviroDIYPOST(dataLogger, 
calls   dataPublisher::  (no MS_DBG)
    setToken(registrationToken);
    _baseLogger->setSamplingFeatureUUID(samplingFeatureUUID);

I've commented then out in my local copy

**Comment by neilh10** [comment]
Further thoughts: as they are in constructors these are extremely hard problems to find. 

That is it fails before it gets to Setup(), where a basic blink() or a Serial, out shows program control.  
I've had to go through and do #ifdef s to find failures - for the ARM compilers - though of course this does work for AVR . Go figure.!

The basis of UART debugging is that there always needs to be traceable stable environment.  With a program simulator (typical Win or Linux) or  JTAG emulator ($$) these problems can be found 

Personally, I plan when I can,  to move to more of 
Logger *dataLogger;
xxxx
setup() {
Serial.begin(xx)
xxx
*dataLogger = new Logger; //supports MS_DBG
}
as it has better management and clearer what is going on in the embedded startup environment.

**Pull request merged**
