### PR TITLE
Merge Y533 ORP getValues() fixes

### PR DESCRIPTION
**Pull request by aufdenkampe**
@SRGDamia1, this PR represents a series of fixes associated with https://github.com/EnviroDIY/YosemitechModbus/issues/19 and also propagated into this library.

The only outstanding issue is that the PlatformIO Library Registry hasn't picked up the latest version of YosemitechModbus (v0.2.5). I must clearly have something wrong with https://github.com/EnviroDIY/YosemitechModbus/blob/master/library.json. Any suggestions?

Last, I'm not sure whether this should be merged into `master`, `develop`, or one of your recent feature branches. I'll let you pick, and adjust the version numbers accordingly as you merge.

@GArrigotti-cws is starting to use these fixes for his deployments, so keep us informed of your plan. Right now, we're just using this branch as a libdep.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Please add your changes to the change log!

**Comment by aufdenkampe** [comment]
We're getting things to work with our `platformio.ini` library dependencies looking like this:

```ini
lib_deps =
    https://github.com/EnviroDIY/ModularSensors.git#y533_ORP
    ;  ^^ Use this when if you want to pull from this branch
    https://github.com/EnviroDIY/YosemitechModbus.git#v0.2.5
    ;  ^^ Use this only because PlatformIO Library Registry hasn't pick up this version
```

**Comment by aufdenkampe** [comment]
@SRGDamia1, I noticed your new ChangeLog! Thanks for setting that up. I think I already updated that properly. There wasn't much to add.

**Comment by SRGDamia1** [comment]
Sorry, the change log comment is posted automatically if GitHub sees a PR without change log modifications.  

The PlatformIO registry has the Yosemitech 0.2.5 listed now:  https://platformio.org/lib/show/2078/YosemitechModbus.  I've set up GitHub actions in many of the repos to automatically publish a new library package when a release is made, but it looks like I haven't set up that one yet.  The PlatformIO registry does tend to lag by up to 24 hours or so, even if you manually publish a new package.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you! 

I hadn't realized that we needed to push updates to the PlatformIO Library Registry. I had always thought that they did that automatically once a library is registered. Thanks for automating that now for this one and for automating it for most of our libraries!

**Comment by SRGDamia1** [comment]
The pio registry still sweeps looking for changes, but they're registered a little faster if you push the package yourself.  It's still not instant, though.

**Comment by SRGDamia1** [comment]
Something's failing with the mega and SoftwareWire.  I'm not sure why.

**Comment by SRGDamia1** [comment]
It's an issue with the latest version of SoftwareWire:  https://github.com/Testato/SoftwareWire/issues/33

I merged develop into this and pinned the old version of software wire.  We'll see if this works.

**Comment by SRGDamia1** [comment]
Grumble.. pinning the version works for PIO but not the Arduino CLI.  I'll have to look for another fix.

**Pull request merged**
