### PR TITLE
Develop to Master

### PR DESCRIPTION
**Pull request by SRGDamia1**
@aufdenkampe if you can test this, I'd like to get the fixes I made to the timing for stabilization push and released on master.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for all of your work yesterday afternoon fixing the timing bug that didn't allow for the long warm up times for the Y4000 sonde. It was also really helpful to learn that it is easy to change the length of the time for sensor update cycles, from the 2 minute default interval to something longer. Can you point me to that place in code again?

I'll do the testing today and let you know, hopefully by early afternoon.

**Comment by SRGDamia1** [comment]
@aufdenkampe  - After thinking on it a bit more, I decided that the magical 2-minute interval was just not a good idea at all.  It doesn't scale well and is rather mysterious in the code.  I changed the base variable object's getValue function to have a boolean input that specifies whether you want the parent sensor to update or not.  By default, getValue() (and getValueString()) will not ask the parent sensor to update the value, they will simply return the last value the variable object was notified of, or -9999 if the sensor has never given the variable a value.  If you want the variable's parent sensor to run an update before returning the variable's value, you must specify getValue(true) (or getValueString(true)).

**Comment by fisherba** [comment]
@SRGDamia1 This may or may not be related to this merge (but I know you've done a lot of work on SDI12 in recent months), the SDI12 work might still have issues. I started running a 5TM along with several other sensors on Friday morning and the 5TM is very spotty about when it is taking good measurements. See here: http://data.envirodiy.org/sites/NLP01/.

**Comment by SRGDamia1** [comment]
@fisherba - I'm putting the 5TM problem in a separate issue (#135)

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'm finally getting to testing this, and so far it looks good. I'm getting values for the Y4000 sonde, which I all I have attached at this point. Nothing else looks funky, *except* I'm getting 0.00 for values from the Keller and Bosch BME280 sensors, rather than -9999. The RainCounterI2C is correctly giving -9999.

@SRGDamia1, Should I expect -9999 when sensors aren't attached?

In the meanwhile, I'll attache the other sensors.

**Comment by aufdenkampe** [comment]
I just attached all the other sensors, and everything seems to be working, with no brown-outs or weird output! Yay! I still have issues with the SIM800 connecting, and the RainCounterI2C isn't reporting a value, but I consider those separate issues for now.

Let's merge! Thanks @SRGDamia1 , @fisherba  and @bschulz1701  for all your hard work that is in this update!

**Comment by SRGDamia1** [comment]
Getting the -9999 depends on the sensor setup. In some sensors the code just can tell if the sensor returned a real zero or some sort of serial time out happened, which generally causes a zero return. I will try to look at the Keller and Bme280 to see what's up with them.

**Comment by SRGDamia1** [comment]
Can you create two issues on those for me?

**Comment by SRGDamia1** [comment]
The Keller problem should be fixed at the level of the Keller library.  As currently written, the ModularSensors library has no way of knowing if the getValues received 0 because the modbus call failed or if the sensor truly returned 0.

**Pull request merged**
