### PR TITLE
Merge 'MS5803-pressure' into Develop

### PR DESCRIPTION
**Pull request by aufdenkampe**
First testing by @fisherba

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for these updates and fixes. We're still having issues getting good values out of this in the example. I must have broken something with @bschulz1701 code when I updated his Lib files to the new timing stuff. I'll try to get it fixed today.

**Comment by bschulz1701** [comment]
@aufdenkampe and @SRGDamia1 feel free to call me or message me specific issues if you are trying to work through the code, I think initially it was pretty well documented (at least the math was) but my fix was not as well done. 

And by good values, do you mean not -9999 or reasonable values?

**Comment by SRGDamia1** [comment]
I don't have one of these sensors to test, but I made some minor changes to the MS5803 library to fix some compiler errors/warnings.

**Comment by SRGDamia1** [comment]
I also added some issues in the original MS5803 repo.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for all your help this morning. You got to some of that stuff before I even asked. Thanks.

@bschulz1701, I'm still getting -9999.00 values for both Temperature and Pressure from the sensor when running the simple_logging.ino in ModularSensors. I'm getting good values from the demo script at https://github.com/EnviroDIY/MS5803/tree/master/examples/MS5803_Demo, so I'm still a bit confused. Any would be much appreciated!

**Comment by aufdenkampe** [comment]
@bschulz1701, thanks for that idea about the address possibly being wrong. Unfortunately, that didn't seem to do it, and I confirmed again, after all the latest updates to https://github.com/EnviroDIY/MS5803, that the demo works well there using address 0x76.

@bschulz1701, could you help me figure this out? @SRGDamia1 is done with her edits for the day.

**Comment by aufdenkampe** [comment]
That works for me too! Thank you @bschulz1701 & @SRGDamia1 !

**Pull request merged**
