### PR TITLE
Xbee fixes

### PR DESCRIPTION
**Pull request by SRGDamia1**

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Please add your changes to the change log!

**Comment by neilh10** [comment]
This would be release 0.34.1  in https://github.com/EnviroDIY/ModularSensors/blob/develop/ChangeLog.md ?

**Comment by neilh10** [comment]
oops I see its gone into master - no (develop)

**Comment by neilh10** [comment]
[0.34.1]
#347 -WiFi S6B stability changes - needs testing

Not clear where an update would go, I don't appear to have write permission
image

**Comment by SRGDamia1** [comment]
Oops, this was meant to go to develop. But, no, you don't have permissions on this repo, so you would need to change the change log, submit a PR to xbee fixes and then that would move up.

That comment is automatically generated whenever a pull request is created without seeing changes to the changelog file.  It just gets my name.

**Comment by neilh10** [comment]
I've pulled in the (develop) and done testing on it. Looking good.
Also can now see how you are doing the metaData updates and for Digi LTE. 
Many thanks

**Pull request merged**
