### PR TITLE
correction for DigiXbee3GBypass.cpp - it fails with MS_DIGIXBEELTEBYP…

### PR DESCRIPTION
**Pull request by neilh10**
Needs MS_DIGIXBEE3GBYPASS_DEBUG_DEEP

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Thanks for the catch!

**Comment by neilh10** [comment]
Great new classes. The new style debugging is working for me, and so easy to now turn on/off.

I'm trying to enable StreamDebugger/ MS_DIGIXBEEWIFI_DEBUG_DEEP on DigiS6B WiFi/Autonomo (tgt is Digi XB3-C-A2 LTE but also appears for DigiS6B can't get AT cmd trace.).   
It worked OK showing AT cmds for MS_DIGIXBEEWIFI_DEBUG_DEEP DigiWiFi/Mayfly - but not for MS_DIGIXBEEWIFI_DEBUG_DEEP DigiWiFi/Autonomo. 
So possibly something to do with switch between AVR to ARM libs.  Any thoughts on areas to look for?

**Comment by neilh10** [comment]
Oops - I got it - I need to define DEEP_DEBUGGING_SERIAL_OUTPUT to output stream.

**Comment by neilh10** [comment]
So using the target SAMD21/Autonomo Arm I'm still  turns out there are still problems with arm based compilers both in getting AT cmd output with DEEP_DEBUG  
For modems\DigiXBeeLTEBypass.h  
I still need to add:
```
#ifdef MS_DIGIXBEELTEBYPASS_DEBUG_DEEP
#define MS_DEBUGGING_DEEP "DigiXBeeLTEBypassD"
#endif
#undef MS_DEBUGGING_DEEP
```
even through it appears "DigiXBeeLTEBypassD" is never used .

But it works OK as it stands with DigiXBeeWifi
It seems to me its got very complicated with adding  DEEP_DEBUGGING_SERIAL_OUTPUT .

**Comment by SRGDamia1** [comment]
Hm. I don't think I've ever tried to use that deep debugging with the SAMD board. I do most of my testing on the Mayfly and usually only try the "production" code on the SAMD. I can try to look into it.

**Comment by neilh10** [comment]
Yeah interesting (!@*&). Possibly something slightly different with the templates implementation between AVR and ARM.  I haven't dug into the subtleties of the differences.  For the *Bypass.cpp I guess its academic.

**Pull request merged**
