### PR TITLE
Un-Style changed modemLast

### PR DESCRIPTION
**Pull request by SRGDamia1**
A fix-up of #302 without the style changes

### CODE REVIEW

**Comment by neilh10** [comment]
Hey Thanks. So much easier to follow. 
I'm still getting the same issue . I'm using the Xbee3 LTR-M  ... any insights appreciated.

https://github.com/neilh10/ModularSensors/tree/modemLast2_nh/examples/logging_to_MMW

I'm using the chip temperature, as its a non-zero number, and can vary slightly
It is retrieved from chip:

Temperature: 22.00 <--DigiXBeeCellularTransparent

and stored in  _priorXX
The result is 
 \/---- Line Saved to SD Card ----\/
2020-02-12 10:35:00,7,4.594,-9999,-9999,-9999.0

I have ...
Variable *variableList[] = {
    new ProcessorStats_SampleNumber(&mcuBoard, "a5d01a6e-5328-4ec8-9ab7-1110720b304e"),
    new ProcessorStats_Battery(&mcuBoard, "0f9c6292-3646-4ab6-8aa3-ca542d5eee49"),
    new Modem_RSSI(&modem,          "08a02c91-5336-4b98-999e-9867cb1c80ae"),
    new Modem_SignalPercent(&modem, "988edc32-629f-4fc6-8ab2-59ef2fa81c9c"),
    new Modem_Temp(&modem, "a3b360bb-683f-4fb3-b720-67f0d585b9a0"),
};
So I think VariableBase is retrieving ... priorXX in  LoggerModem, but I've really dug into this section ... so maybe I've setup something wrong.

For LoggerModem.cpp#449 I added MS_DBG(F("PRIOR Modem Chip Temperature:"), _priorModemTemp);

On the debug trace I now get

`Starting measurement on EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 4.59 in result array for variable 0 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 11997.00 in result array for variable 1 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 2.00 in result array for variable 2 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Power to EnviroDIY Mayfly at EnviroDIY Mayfly is not controlled by this library. <--SensorBase
Averaging results from EnviroDIY Mayfly at EnviroDIY Mayfly over 1 reading[s] <--SensorBase
    ->Result # 0 : 4.59 <--SensorBase
    ->Result # 1 : 11997.00 <--SensorBase
    ->Result # 2 : 2.00 <--SensorBase
Notifying variables registered to EnviroDIY Mayfly at EnviroDIY Mayfly of value update. <--SensorBase
Sending value update from EnviroDIY Mayfly at EnviroDIY Mayfly to variable 0 which is batteryVoltage ... <--SensorBase
... received 4.59 <--VariableBase
EnviroDIY Mayfly at EnviroDIY Mayfly has no variable registered for return value 1 !  No update sent! <--SensorBase
Sending value update from EnviroDIY Mayfly at EnviroDIY Mayfly to variable 2 which is sequenceNumber ... <--SensorBase
... received 2.00 <--VariableBase
Successfully connected to SD Card with card/slave select on pin 12 <--LoggerBase
Opened existing file: XXXXX_2020-02-12.csv <--LoggerBase
**PRIOR Modem Chip Temperature: 24.00 <--LoggerModem**

 \/---- Line Saved to SD Card ----\/
2020-02-12 11:30:00,2,4.594,-9999,-9999,**PRIOR Modem Chip Temperature: -9999.00 <--LoggerModem**
-9999.0


Waking up Digi XBee3 Cellular LTE-M ... <--LoggerBase
Running wake function for Digi XBee3 Cellular LTE-M <--DigiXBeeCellularTransparent
Setting pin 23 LOW to wake Digi XBee3 Cellular LTE-M <--DigiXBeeCellularTransparent
Turning off airplane mode... <--DigiXBeeCellularTransparent

Waiting up to 15000 ms for Digi XBee3 Cellular LTE-M to respond to AT commands... <--DigiXBeeCellularTransparent
... AT OK after 504 milliseconds! <--DigiXBeeCellularTransparent
Digi XBee3 Cellular LTE-M should be awake and ready to go. <--DigiXBeeCellularTransparent
Connecting to the Internet... <--LoggerBase

Waiting up to 50 seconds for cellular network registration... <--DigiXBeeCellularTransparent
... Connected after 6518 milliseconds. <--DigiXBeeCellularTransparent
Sending out remote data. <--LoggerBase

Sending data to [ 0 ] data.envirodiy.org
**PRIOR Modem Chip Temperature: -9999.00 <--LoggerModem
PRIOR Modem Chip Temperature: -9999.00 <--LoggerModem**
POST /api/data-stream/ HTTP/1.1
`

**Comment by SRGDamia1** [comment]
Yes, found and fixed. I was trying to un-set the valves after they had been read out once with the thought that the value should only be accepted one as prior and after that there would be no value... but I was effectively immediately un-setting then.

**Comment by neilh10** [comment]
Yup that fix works for me over the first few cycles with the Digi LTE-M.  
I'll try the Xbee WiFi next, possibly tomorrow.

**Comment by neilh10** [comment]
Yup its working for three variables on Xbee WiFi S6. 
Probably work for the rest.
I'll leave it running with the WiFi S6 overnight and see what happens.
 Great work.  I don't think I can do any other testing.

A thought; the first pass is always going to have the Modems metadata at -9999. 

 \/---- Line Saved to SD Card ----\/
2000-01-01 00:10:00,2,4.609,-9999,-9999,-9999.0

This really defines an extreme starting point, and the auto-scaling visualization on the graph makes subsequent real readings pretty hard to investigate . 
Then the real data is closer about 0.
 \/---- Line Saved to SD Card ----\/
2020-02-13 14:55:00,3,4.609,-71,67,29.0
RSSI -71.67 db
% Signal Strength 67 %
Temperature (C) 29.0

Another way might be to init to -0.00123. Its clearly an distinctive number if it occurs each cycle, but won't interfere with standard readings. Being close to 0.0 it also helps  the scaling. 
So just an idea.

**Comment by SRGDamia1** [comment]
That is a good point; I hadn't even thought of it.

**Comment by neilh10** [comment]
A further thought on init values, might be for all modules do 
#ifndef SENSORINT_UNINIT
#define SENSORINT_UNINIT -1
#endif //SENSORINT_UNINIT

#ifndef SENSORFL_UNINIT
#define SENSORFL_UNINIT -0.0123
#endif //SENSORFL_UNINIT

int16_t loggerModem::_priorRSSI = SENSORINT_UNINIT;
float loggerModem::_priorModemTemp = SENSORFL_UNINIT;

**Pull request merged**
