### PR TITLE
Merge modemLast into develop

### PR DESCRIPTION
**Pull request by aufdenkampe**
@SRGDamia1, is this ready for testing and/or merging?

### CODE REVIEW

**Comment by SRGDamia1** [comment]
I'm sorry; I missed this.  I honestly don't remember.

**Comment by aufdenkampe** [comment]
No worries. I'm behind on my EnviroDIY GitHub bookkeeping on lots of fronts. Hoping to get back on top of it soon, as it looks like I'll be doing a few workshops early this winter and another round of deployments by early spring.

**Comment by SRGDamia1** [comment]
I think the big thing needed before pulling this in is testing.  I think all the major overhauling is done.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for all of your work on this!
I won't have time to test until the second half of January, but will be able to do testing then when I get started on some deployment and development work.

In the meanwhile, can you list out the changes & potential benefits of this overhaul (i.e. draft release notes)?

**Comment by neilh10** [comment]
Gosh yes good to see this being merged in. I was hoping to get to this, but I have some time critical objectives I have to complete before trying it, so not sure I can get to it this week.

**Comment by SRGDamia1** [comment]
It's definitely ready for testing, probably for merging.

I have done at least cursory testing of:
UBee U201
XBee3 LTE bypass
XBee3 LTE transparent
ESP8266
2GBee

I haven't even run the code for these
[ ] XBee Wifi
[ ] XBee 3G bypass
[ ] XBee 3G transparent
[ ] SIM800 Fona
[ ] Sequans Monarch

There are a few other stray things to be tested.  I need to figure out what they are.

**Comment by neilh10** [comment]
I'll aim to exercise the XBee WiFi and the XBee 3 LTE Transparent.
However unlikely to get to it this week.

**Comment by SRGDamia1** [comment]
Thank you!

I ran quickly on the WiFi and it seemed to work fine, but I ran for about 5 minutes total.

**Comment by neilh10** [comment]
@SRGDamia1 something seems to be amis with v0.24.1  - any suggestions.

 I'm trying to have a precise workflow using platformio/VSC and build this and feedback.
From git.bash on my windowsPC,
I have a ModularSensors setup
env03/ModularSensors   v0.23.16
env03ts/ModularSensors  v0.24.1
So for 
cd /d/usr/a/Documents/Arduino/env03ts/ModularSensors

$ git remote -v
..
upstream        https://github.com/EnviroDIY/ModularSensors.git (fetch)
upstream        https://github.com/EnviroDIY/ModularSensors.git 
$git checkout --track upstream/modemLast
env03ts/ModularSensors (modemLast) 
$ git checkout -b modemLast_nh1
Switched to a new branch 'modemLast_nh1'
env03ts/ModularSensors (modemLast_nh1)


From platformio/VSC I do  open_folder  env03ts\ModularSensors\examples\logging_to_MMW
and then build

Processing mayfly (board: mayfly; platform: atmelavr; framework: arduino)
-----------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/mayfly.html
PLATFORM: Atmel AVR 2.0.0 > EnviroDIY Mayfly
HARDWARE: ATMEGA1284P 8MHz, 16KB RAM, 127KB Flash
PACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-arduino-avr 5.0.0
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Looking for EnviroDIY_ModularSensors library in registry
Found: https://platformio.org/lib/show/1648/EnviroDIY_ModularSensors
LibraryManager: Installing id=1648 @ 0.24.1
UndefinedPackageVersion: Could not find a version that satisfies the requirement '0.24.1' for your system 'windows_amd64':
  File "C:\Users\neilh77a\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 151:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\neilh77a\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 605:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\neilh77a\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 286:


If I build it with the 0.23.16 version it has no problems
Processing mayfly (board: mayfly; platform: atmelavr; framework: arduino)
------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/mayfly.html
PLATFORM: Atmel AVR 2.0.0 > EnviroDIY Mayfly
HARDWARE: ATMEGA1284P 8MHz, 16KB RAM, 127KB Flash
PACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-arduino-avr 5.0.0
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 12 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <EnviroDIY_ModularSensors> 0.23.16

**Comment by SRGDamia1** [comment]
It sounds like PlatformIO is trying to look up the library from their library registry and is erroring out because that version doesn't exist there. Your platformio.ini file has the git repo and branch listed, not just the library name, right? If you only use a name it will go to the registry and stop there. The library is listed under the master branch and the automated tools PlatformIO uses to keep its library registry up-to-date only register a new version when there has been a release or the version in library.json on the master branch changes.

Apart from you project ini, diid you create a library.json for your own branch that list ModularSensors as a dependency? If the library is listed by name/version in any of the recursive dependencies (1st the ini, then the dependencies in the library.json of each of those, etc) the library manager will go to the registry and not github. It has to be listed by the repo url/branch every single place. Sometimes if you have a git version listed in the very first dependency it tries to install the recursive installations will see the dependency as already fulfilled, but I've had that fail for me. Usually I get messed up if I try to do something like use SensorModbusMaster from git but then it sees SensorModbusMaster listed by name in the Yosemitech dependencies and tries to install twice or crashes out. (That particular dependency chain bites me all the time.)

**Comment by neilh10** [comment]
Gosh thanks for the late night thoughts, and pointers. 
I guess I needed to know was it a simple fix as I haven't gone into the production build env,  as I'm trying to support verification testing for the comms, 
I'm trying to figure out what is the  workflow for doing this. 
Its a distributed ~ and amazing ~ environment, but as you say and I've found out easy to trip over evolving pointers, in this case I think to the 0.24.1  - which I don't have any idea how that works.

I started examples/logging_to_MMW as what I thought was the most stable - it only needs one target environment to work, and should be scaleable for the physical comms types.

After your pointer I changed the following and it built for me. Not tested yet :) Again many thanks.

 env03ts/examples/logging_to_MMW/platformio.ini 
[platformio]
src_dir =.

[env:mayfly]
lib_deps =
    https://github.com/EnviroDIY/ModularSensors.git#modemLast
    https://github.com/EnviroDIY/YosemitechModbus

**Comment by neilh10** [comment]
I got a test build going on MMW,  but haven't managed to get the Digi XBee3 Cellular LTE-M modem sensors to be saved.  The sensors including LTE temperature are read off the modem after the POST ok, but then never get into the next cycle of sensors.

I thought I had posted about ... but now can't find that post. :(

**I set up a mafly 0.5b with LTE on Modem Board and**
Now running logging_to MMW.ino on Logger XXXXX

Using ModularSensors Library version 0.24.1


**small set of sensors**
a5d01a6e-5328-4ec8-9ab7-1110720b304e -> SampNum
0f9c6292-3646-4ab6-8aa3-ca542d5eee49 -> Battery
08a02c91-5336-4b98-999e-9867cb1c80ae -> RSSI
988edc32-629f-4fc6-8ab2-59ef2fa81c9c -> signalPercent
a3b360bb-683f-4fb3-b720-67f0d585b9a0 -> modemTemp

**the 1st pass**
Averaging results from EnviroDIY Mayfly at EnviroDIY Mayfly over 1 reading[s] <--SensorBase
    ->Result # 0 : 4.59 <--SensorBase
    ->Result # 1 : 11612.00 <--SensorBase
    ->Result # 2 : 2.00 <--SensorBase

**and** 

 \/---- Line Saved to SD Card ----\/
2020-01-28 11:15:00,2,4.594,-9999,-9999,-9999.0

**then posts and gets Modem parms**

-- Response Code --
201
Updating modem metadata... <--LoggerBase
Entering Command Mode: <--DigiXBeeCellularTransparent
Getting signal quality: <--DigiXBeeCellularTransparent
Raw signal quality: 0 <--DigiXBeeCellularTransparent
CURRENT RSSI: 0 <--DigiXBeeCellularTransparent
CURRENT Percent signal strength: 0 <--DigiXBeeCellularTransparent
Getting chip temperature: <--DigiXBeeCellularTransparent
Getting temperature: <--DigiXBeeCellularTransparent
Temperature: 24.00 <--DigiXBeeCellularTransparent
CURRENT Modem temperature: 24.00 <--DigiXBeeCellularTransparent
Leaving Command Mode: <--DigiXBeeCellularTransparent
Disconnecting from the Internet... <--LoggerBase

when wakes again


     zzzZZ Processor is now awake! <--LoggerBase
Current Unix Timestamp: 1580210400 -> 2020-01-28T11:20:00-08:00 <--LoggerBase
Logging interval in seconds: 300 <--LoggerBase
Mod of Logging Interval: 0 <--LoggerBase
Time marked at (unix): 1580210400 <--LoggerBase
Time to log! <--LoggerBase
------------------------------------------
Running a complete sensor update... <--LoggerBase
Clearing value array for EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Power to EnviroDIY Mayfly at EnviroDIY Mayfly is not controlled by this library. <--SensorBase
Starting measurement on EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 4.59 in result array for variable 0 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 11612.00 in result array for variable 1 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Putting 3.00 in result array for variable 2 from EnviroDIY Mayfly at EnviroDIY Mayfly <--SensorBase
Power to EnviroDIY Mayfly at EnviroDIY Mayfly is not controlled by this library. <--SensorBase
Averaging results from EnviroDIY Mayfly at EnviroDIY Mayfly over 1 reading[s] <--SensorBase
    ->Result # 0 : 4.59 <--SensorBase
    ->Result # 1 : 11612.00 <--SensorBase
    ->Result # 2 : 3.00 <--SensorBase
Notifying variables registered to EnviroDIY Mayfly at EnviroDIY Mayfly of value update. <--SensorBase
Sending value update from EnviroDIY Mayfly at EnviroDIY Mayfly to variable 0 which is batteryVoltage ... <--SensorBase
... received 4.59 <--VariableBase
EnviroDIY Mayfly at EnviroDIY Mayfly has no variable registered for return value 1 !  No update sent! <--SensorBase
Sending value update from EnviroDIY Mayfly at EnviroDIY Mayfly to variable 2 which is sequenceNumber ... <--SensorBase
... received 3.00 <--VariableBase
Successfully connected to SD Card with card/slave select on pin 12 <--LoggerBase
Opened existing file: XXXXX_2020-01-28.csv <--LoggerBase

 \/---- Line Saved to SD Card ----\/
2020-01-28 11:20:00,3,4.594,-9999,-9999,-9999.0

I've attached the full log file I took.

A challenge I've had, is that I haven't been able to follow this features specific code changes and understand them, and where the modem readings might be getting lost .     
On Jan 10 an "Apply Style Sheet" caused 128 files to have a change, and not just white space, so its been very hard to decode the new code associated with this feature.     
I do appreciate having a nice uniform coding style, but personally, I try to apply refactoring changes  in between releases so that they can be marked as refactoring
https://github.com/EnviroDIY/ModularSensors/commit/1b1d6bd28e2eb39554b75ff0ef33d5c1f155b8fb 

[tty200128-1111mayflyLte.txt](https://github.com/EnviroDIY/ModularSensors/files/4183499/tty200128-1111mayflyLte.txt)

**Comment by SRGDamia1** [comment]
@neilh10 - I'm sorry.  The style changes were a total botch up by me.  I accidentally changed the setting in VSCode to reformat on save and then everything got changed and instead of smartly undoing that, I changed more stuff.  I did a rebase to remove some of that and have a new PR #306 for it.

**Pull request closed without merging**
