### PR TITLE
Concurrent measurements

### PR DESCRIPTION
**Pull request by SRGDamia1**
Adds support for taking measurements concurrently - that is, start measuring a, then b, then c without waiting for results, then come back to a, then b, then c and get results.  Previously we were waiting for results before moving the next sensor.  Also adds support for averaging as many readings as desired from ALL sensors.

- Retained the update() function, which WILL wait for results.
- Added two new functions to deal with concurrency:  startSingleMeasurement and addSingleMeasurementResult.
    - If only dealing with a single sensor, USE THE UPDATE FUNCTION.  The other two functions skip very important steps like notifying variables that new results exist
- CHANGED SOME CONSTRUCTORS - the examples have been updated, but older examples for Maxbotix and Yosemitech sensors will no longer work.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
Note.. TravisCI won't pass until library updates make it thorough the PlatformIO registries.

**Comment by aufdenkampe** [comment]
This was my output from a modified version of `logging_to_EnviroDIY​.ino`, based on last night's commits.
Looks like there might be an arithmetic error in some of the new averaging functions.

```
Now running logging_to_EnviroDIY.ino on Logger Mayfly_170010
Logger timezone is UTC-5
RTC timezone is UTC
Initializing logger Mayfly_170010 to record at 5.00 minute intervals ...    ... Success!
Current RTC time is: 2000-01-27T16:07:08-05:00
Attempting to synchronize RTC with NIST
Bad timestamp, skipping sync.
Successfully connected to SD Card with card/slave select on pin 12
Data will be saved as Mayfly_170010_2000-01-27.csv...   ... File created!
Logger setup finished!
------------------------------------------

Push button NOW to enter debug mode.
------------------------------------------
Entering debug mode
------------------------------------------
Current logger time is 2000-01-27T16:10:16-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 24.25 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 7389 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 21.71 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 0.00 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 20.55 degreeCelsius
    -----------------------
Current modem signal is 55%
------------------------------------------
Current logger time is 2000-01-27T16:10:39-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 9.461 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 21446 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 48.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 9400 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 26.08 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 74.71 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 24.74 degreeCelsius
    -----------------------
Current modem signal is 55%
------------------------------------------
Current logger time is 2000-01-27T16:11:13-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 14.191 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 32169 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 73.00 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 11417 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -3999.6 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -3981.33 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 212.19 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 25.70 degreeCelsius
    -----------------------
Current modem signal is 55%
```

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for that fix! Here is my output from the code with your "Added missing clear values" commit. The arithmetic problem is solved, and the turbidity sensor values look good. However, 
the MaxSonar and Yosemitech 520 Conductivity sensors are producing weird results.
* MaxSonar values don't seem right. Note my first values was 7389 millimeter, which is higher than the max for this sensor, then after positioning it about 55 cm away from a box, the readings were 3564 millimeter.
* The Y520 Conductivity values alternate between reasonable numbers for one measurement, then crazy negative numbers for another, then back to reasonable numbers, in no real pattern.

Here's the output.

```
Now running logging_to_EnviroDIY.ino on Logger Mayfly_170010
Logger timezone is UTC-5
RTC timezone is UTC
Initializing logger Mayfly_170010 to record at 5.00 minute intervals ...    ... Success!
Current RTC time is: 2000-01-27T18:27:50-05:00
Attempting to synchronize RTC with NIST
Bad timestamp, skipping sync.
Successfully connected to SD Card with card/slave select on pin 12
Data will be saved as Mayfly_170010_2000-01-27.csv...   ... File created!
Logger setup finished!
------------------------------------------

Push button NOW to enter debug mode.
------------------------------------------
Entering debug mode
------------------------------------------
Current logger time is 2000-01-27T18:30:37-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 7389 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -1999.8 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -1981.97 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 0.00 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.27 degreeCelsius
    -----------------------
Current modem signal is 52%
------------------------------------------
Current logger time is 2000-01-27T18:31:05-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 2011 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -1999.8 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -1981.99 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 106.41 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.38 degreeCelsius
    -----------------------
Current modem signal is 55%
------------------------------------------
Current logger time is 2000-01-27T18:31:38-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 2017 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -3999.6 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -3986.23 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 149.93 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.38 degreeCelsius
    -----------------------
Current modem signal is 55%
------------------------------------------
Current logger time is 2000-01-27T18:32:01-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.745 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.75 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 517 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 22.27 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 149.94 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.42 degreeCelsius
    -----------------------
Current modem signal is 55%
------------------------------------------
Current logger time is 2000-01-27T18:32:30-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.75 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 5000 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -1999.8 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -1981.99 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 150.09 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.50 degreeCelsius
    -----------------------
Current modem signal is 55%

.
.
.
------------------------------------------
Current logger time is 2000-01-27T18:37:12-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 3562 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -3999.6 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -3986.30 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 1.31 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.75 degreeCelsius
    -----------------------
Current modem signal is 52%
------------------------------------------
Current logger time is 2000-01-27T18:37:35-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 3562 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 22.15 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 1.34 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.75 degreeCelsius
    -----------------------
Current modem signal is 52%
------------------------------------------
Current logger time is 2000-01-27T18:37:58-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 3562 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 22.12 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 1.31 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.75 degreeCelsius
    -----------------------
Current modem signal is 48%
------------------------------------------
Current logger time is 2000-01-27T18:38:21-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.730 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.50 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 3562 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is 0.0 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is 22.09 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 1.33 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.75 degreeCelsius
    -----------------------
Current modem signal is 52%
------------------------------------------
Current logger time is 2000-01-27T18:38:49-05:00
    -----------------------
EnviroDIY Mayfly at EnviroDIY Mayfly reports batteryVoltage is 4.745 Volt
EnviroDIY Mayfly at EnviroDIY Mayfly reports Free SRAM is 10723 Bit
MaximDS3231 at I2C_0x68 reports temperatureRTC is 25.25 degreeCelsius
MaxBotixMaxSonar at sonarStream reports distance is 3564 millimeter
YosemitechY520 at modbus_0x01 reports specificConductance is -1999.8 microsiemenPerCentimeter
YosemitechY520 at modbus_0x01 reports temperature is -1982.14 degreeCelsius
YosemitechY511 at modbus_0x03 reports turbidity is 1.27 nephelometricTurbidityUnit
YosemitechY511 at modbus_0x03 reports temperature is 22.75 degreeCelsius
    -----------------------
Current modem signal is 52%
------------------------------------------

**Comment by aufdenkampe** [comment]
@SRGDamia1. Update! Once the logger went out of debugging mode, things are looking good.

```

End of debug mode.
------------------------------------------

 -- Unable to Establish Connection to EnviroDIY Data Portal -- 
 -- Response Code -- 
504

 \/---- Line Saved to SD Card ----\/ 
2000-01-27 18:42:00,4.730,10720,25.00,546,0.0,21.90,0.00,22.50
------------------------------------------

------------------------------------------

 -- Unable to Establish Connection to EnviroDIY Data Portal -- 
 -- Response Code -- 
504

 \/---- Line Saved to SD Card ----\/ 
2000-01-27 18:45:00,4.730,10720,25.25,539,0.0,21.87,0.00,22.63
------------------------------------------

------------------------------------------

 -- Unable to Establish Connection to EnviroDIY Data Portal -- 
 -- Response Code -- 
504

 \/---- Line Saved to SD Card ----\/ 
2000-01-27 18:48:00,4.730,10720,25.50,539,0.0,21.80,0.60,22.63
------------------------------------------
```

**Comment by aufdenkampe** [comment]
@SRGDamia1, I just noticed one weird thing. My code is set to `loggingInterval = 5`, but my timestamps are 2-4 minutes apart (they are not even always the same). What is going on there?

**Comment by aufdenkampe** [comment]
@SRGDamia1, good news! Radio working. Rookie Mistake. I forgot to set `const char *apn = "apn.konekt.io"`.

Clock was therefore reset, and all sensor values (after the first one), are looking good and showing up at http://data.envirodiy.org/sites/RPB-3/.

Unfortunately, the logging interval still seems to be stuck at ~2 minutes, even though I set it to 5 min.
I just created a new issue, #95

**Comment by aufdenkampe** [comment]
@SRGDamia1, there is one last thing to look into. As I mentioned in https://github.com/EnviroDIY/ModularSensors/issues/95#issuecomment-363898898, a good number of Conductivity measurements are bad (large negative numbers) during this 2-minute logging interval. Not sure if its related, but nearly every other conductivity value looks like this when in debug mode.

Any ideas on this? Should we merge anyways then try to continue to debug?

**Pull request merged**
